### ISSUE TITLE
Black textures when playing Azurik on AMD Graphics

### ISSUE THREAD

**Issue by arbitercay** [Cxbx-Reloaded/game-compatibility#1001]
When playing Azurik on AMD graphics, latest stable drivers, Azurik loads in with black textures. Objects come in and out of view when changing viewing angles. When viewing the log, an error reads "AMD Graphics detected, changing to pixel shader 2.x"

Textures load in on Nvidia graphics, although they do tend to flicker in and out of view when moving.
![Screenshot_45-1](https://user-images.githubusercontent.com/66978144/84847557-47da4280-b006-11ea-957e-35a89311a69e.png)

**Comment by Margen67** [comment]
Per-game issues belong in a report: #444
You also didn't use the template.
