### ISSUE TITLE
Scooby Doo - Night Of 100 Frights [TQ-031] (1.01)

### ISSUE THREAD

**Issue by Radaxsly** [Cxbx-Reloaded/game-compatibility#1016]
### Description
The game begins with a into sequence (the developers and that sort of stuff, then a video sequence) which is lagging very slowly. The lag continues and at certain points various sound effect audio plays along with the music which repeats untill another sound effect plays and then this repeats. Eventually everying pauses at a point and you cannot carry on.

### Dumps

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4878754/KrnlDebug.txt)

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4878686/Xbe.txt)

### Status
**Previous behavior:** 
 None reported

**Current behavior:**
Slow, laggy boot. Freezes midboot and cannot procced. Audio Issues (boot sequence has audio that repeats)

### Screenshots
![Annotation 2020-07-06 133540](https://user-images.githubusercontent.com/26633813/86590713-7194e280-bf90-11ea-8037-0c04dbdd5ed4.png)

### Additional Information
Xbox game is a rip placed in my downloads folder.
I've Allowed Admin Priviledge.

**Comment by Margen67** [comment]
Duplicate of #983
