### ISSUE TITLE
Full Spectrum Warrior: Ten Hammers [TQ-248] [1.01]

### ISSUE THREAD

**Issue by bryce13950** [Cxbx-Reloaded/game-compatibility#1019]
### Description

The game immediately crashes without any error message showing

```

```

### Dumps

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4907570/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4907569/KrnlDebug.txt)

### Status
**Previous behavior:** 

None Reported

**Current behavior:**

Not Booting

**Comment by bryce13950** [comment]
This is a duplicats of #1020 now

**Comment by Margen67** [comment]
Duplicate of #1020
