### ISSUE TITLE
Wallace & Gromit The Curse of the Were-Rabbit

### ISSUE THREAD

**Issue by ss-d49** [Cxbx-Reloaded/game-compatibility#1025]
### Description

The game appears to run properly with sound but no video at all.

```
There is this error in the Debug output: onecore\com\combase\objact\objact.cxx(836)\combase.dll!75F1C59C: (caller: 75F1B56B) ReturnHr(1)tid(27sec)800401F0 ColInitialize has not been called.
```

### Dumps

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4943550/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4943551/Xbe.txt)

### Status
**Previous behavior:** 

**Current behavior:**

Game runs but no video is displayed.

**Comment by Margen67** [comment]
@ss-d49 https://github.com/Cxbx-Reloaded/game-compatibility#issue-titles

**Comment by Margen67** [comment]
Replaced with #1026
