### ISSUE TITLE
Dungeons And Dragons Heroes

### ISSUE THREAD

**Issue by WolfmanMR25** [Cxbx-Reloaded/game-compatibility#1027]
### Description

```

```

### Dumps

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4948329/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4948323/KrnlDebug.txt)
](url)

### Status
**Previous behavior:** 

None reported

**Current behavior:**

Screen flickering. Turns white sometimes. There's Sound but all messed up. Few minutes of really slow gameplay, it completely freezes. So it partially works on Cxbx-Reloaded-CI-4d06712

### Additional Information
 with and without - speed Hack run on all cores, allow admin privilege and disable pixel shaders

**Comment by WolfmanMR25** [comment]
I did follow the issue template.

**Comment by Margen67** [comment]
No, you didn't. The issue title is wrong.

**Comment by WolfmanMR25** [comment]
Ok, I'll look it over and fix it.

**Comment by Margen67** [comment]
Duplicate of #47
