### ISSUE TITLE
Star Wars: The Clone Wars 

### ISSUE THREAD

**Issue by GTTeancum** [Cxbx-Reloaded/game-compatibility#1029]
### Description

Received a dirty disc error on boot. Attempted with June 30, 2020 and July 18, 2020 builds. This is LA-004 v1.01 (SW: The Clone Wars)

```
There's a problem with the disc you're using. It may be dirty or damaged.
```

### Status
**Previous behavior:** 

**Current behavior:**

Dirty disc on boot

### Additional Information

Ran with all emulator defaults

**Comment by Margen67** [comment]
#1031
