### ISSUE TITLE
Deathrow[US-004][1.03]

### ISSUE THREAD

**Issue by jiangwei4** [Cxbx-Reloaded/game-compatibility#1032]
### Description

```
* Unable to determine default xbox backbuffer
```

### Dumps

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4984420/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4984422/KrnlDebug.txt)

### Status
**Previous behavior:** 

**Current behavior:**

unable  to determine the backbuffer

### Screenshots

![image](https://user-images.githubusercontent.com/15106785/88592169-d908f400-d05d-11ea-8583-bd7fa6bd317d.png)

### Additional Information

I have the same message with the hacks : run xbox thread on all cores

**Comment by Margen67** [comment]
Duplicate of #1033
