### ISSUE TITLE
NBA Ballers: Phenom [IM-34775] [1.70]

### ISSUE THREAD

**Issue by SilasLaspada** [Cxbx-Reloaded/game-compatibility#1037]
### Description

The game crashes soon after boot, only displaying a black screen. Hitting cancel to debug causes it to return straight to the emulator's main window.

```
Received Exception Code 0xC0000005 @ EIP := 0x00145B46(=D3DDevice__m_VertexShader_OFFSET+0x1453b2)
```

### Dumps

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/5119430/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/5119431/KrnlDebug.txt)

### Status
**Previous behavior:** 

None reported.

**Current behavior:**

Crashes soon after boot.

### Screenshots

N/A

### Additional Information

This game is a demo from the Xbox Magazine Issue 56 cover disc.

**Comment by Margen67** [comment]
#1036
