### ISSUE TITLE
Problem when launching Mechassault2: lone wolf

### ISSUE THREAD

**Issue by T1T4N1UM013** [Cxbx-Reloaded/game-compatibility#1042]
### Description

When I want to launch the game (Open default.xbe then Start Emulation), a crash sound is detected and a error popup is displayed after few second
![Sans titre](https://user-images.githubusercontent.com/71092644/92774814-1e7b4980-f39e-11ea-8b72-6a393d2a3a5c.png)

```

```

### Dumps

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/5203687/KrnlDebug.txt)

### Status
**Previous behavior:** 
 None reported

**Current behavior:**
When I want to launch the game (Start Emulation), a error popup is displayed

### Additional Information

If you need any others information about my PC setup:
W10, AMD Ryzen7, CG nvidia 960, 16Go ram
Cxbx-Reloaded
Version fa6387a (sep 8 2020)

**Comment by Margen67** [comment]
#1043
