### ISSUE TITLE
Otogi 2 [FS-004] [1.02]

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [Cxbx-Reloaded/game-compatibility#1070]
### Description

i click on start and ...nothing, dont work needs support
heres a previous report already 
https://github.com/Cxbx-Reloaded/game-compatibility/issues/1050

```

```

### Status
**Previous behavior:** 

**Current behavior:**

**Comment by Margen67** [comment]
If an issue already exists don't create a duplicate. Also, make sure to actually provide useful information next time. This issue is useless.
