### ISSUE TITLE
Breakdown [NM-009] [1.03] 

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [Cxbx-Reloaded/game-compatibility#1071]
### Description

nothing once again , same issue needs proper support , i really love both games and would love to finally be able to play them on pc, oh and see this report already from 2017
https://github.com/Cxbx-Reloaded/game-compatibility/issues/115

```

```

### Status
**Previous behavior:** 

**Current behavior:**

**Comment by Margen67** [comment]
https://github.com/Cxbx-Reloaded/game-compatibility/issues/1070#issuecomment-740301558
