### ISSUE TITLE
Olá gostaria de relatar que o jogo Spartan total warior está travando no loading inicial e sendo meu jogo favorito gostaria que dessem uma atenção pra resolver esse problema que os jogos ficam no loading infinito.

### ISSUE THREAD

**Issue by RafaeruRN** [Cxbx-Reloaded/game-compatibility#1090]
### Description

```

```

### Status
**Previous behavior:** 

**Current behavior:**

**Comment by RafaeruRN** [comment]
![Screenshot_20210521-032909](https://user-images.githubusercontent.com/84505056/119092426-d14b7f00-b9e4-11eb-9e04-71c012f5f208.png)
![Screenshot_20210521-032417](https://user-images.githubusercontent.com/84505056/119092429-d1e41580-b9e4-11eb-89bf-339effb5b24a.png)

**Comment by Margen67** [comment]
This isn't the right emulator. Cxbx-Reloaded doesn't even support Android. Your issue belongs here: https://github.com/jpd002/Play-
