### ISSUE TITLE
Blood Wake [4D530010]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#12]
[Wikipedia](https://en.wikipedia.org/wiki/Blood_Wake)

_From @fatjohnny118 on August 9, 2017 2:50_

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210196/CxbxDebug.txt)
<img width="959" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103172-fa83f950-7c8b-11e7-856d-594397838cdd.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210197/KrnlDebug.txt)
xbe dump below
[Blood Wake.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213261/Blood.Wake.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#654_

**Comment by PatrickvL** [comment]
_From @literalmente-game on August 9, 2017 3:2_

Duplicate from https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/196

**Comment by PatrickvL** [comment]
_From @fatjohnny118 on August 9, 2017 3:3_

sorry i apoligize just trying to aid in the help

**Comment by CakeLancelot** [comment]
Duplicate of #185
