### ISSUE TITLE
Futurama PAL - menue crash - videos added

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#128]
_From @frankyfife on April 16, 2017 13:41_

before 17/04/14 build the game does nothing, now i can reach the menue (but only when vsync is disabled). the menue is ridiculous fast (100-200 fps) and scrolls by itself (no controller used nor configured), then the emulator crahes.

![unbenannt](https://cloud.githubusercontent.com/assets/16177808/25071572/31d633e4-22bb-11e7-8591-38d5a65ac8d8.JPG)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/924307/KrnlDebug.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#373_

**Comment by PatrickvL** [comment]
_From @frankyfife on April 24, 2017 14:40_

Uploaded 2 vids on youtube. With the build from 23th of april the menue is fully accesible ( controller configuration is needed), options and extras r selectable, choose the new game option let the game crash.

there is also a huge white overlay in the top left corner, which make you think the fmv's are not working but they do (as proved with the vid with 4k res).

https://www.youtube.com/watch?v=CGPId7o7Gls (auto res)

https://www.youtube.com/watch?v=0PllvMIEIKY (4k res)

**Comment by PatrickvL** [comment]
I get network errors on both videos

**Comment by PatrickvL** [comment]
_From @frankyfife on April 24, 2017 15:42_

fixed.

**Comment by PatrickvL** [comment]
@Cxbx-Reloaded/issue-maintainers : Please merge #198, #128 and #71 into one issue.

**Comment by CakeLancelot** [comment]
Duplicate of #71. Information transferred, closing this one.
