### ISSUE TITLE
Super Collapse! 2 [?]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#133]
## Issues
 - Menus + Crash

_From @blueshogun96 on April 10, 2017 20:34_

Before Cxbx-Reloaded/Cxbx-Reloaded#350 
![cxbx 2017-04-10 12-52-57-24](https://cloud.githubusercontent.com/assets/5076651/24881224/f8bc6cea-1df1-11e7-81c9-b3ff4ab7828d.png)

After Cxbx-Reloaded/Cxbx-Reloaded#350 
![cxbx 2017-04-10 13-14-28-30](https://cloud.githubusercontent.com/assets/5076651/24881240/0cdf4a58-1df2-11e7-8a01-a9e3be9dfce8.png)

It crashes when trying to go ingame due to a call to XFONT_SetTextHeight @ 0x30E30.  It's quite rare that titles ship with XFONT APIs in use, so I dunno about this one...

Shogun

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#352_

**Comment by PatrickvL** [comment]
_From @LukeUsher on April 10, 2017 20:40_

I see no reason why XFONT_SetTextHeight should fail unpatched, there's possibly something missing/broken further back in the call chain

**Comment by PatrickvL** [comment]
Remarkable how the white "options" texts disappear behind the blue bars, in the "After #350" screenshot

**Comment by PatrickvL** [comment]
_From @blueshogun96 on April 11, 2017 18:52_

@LukeUsher yeah, more than likely.  I've written some really basic examples with XFONT before, but never had any issues out of it.

Shogun

**Comment by Margen67** [comment]
Will reopen once Xbe dump and KrnlDebug.txt are provided.
