### ISSUE TITLE
Bookworm [?] [?]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#134]
_From @blueshogun96 on April 10, 2017 20:26_

![cxbx 2017-04-10 13-24-56-54](https://cloud.githubusercontent.com/assets/5076651/24880966/35f85b7e-1df1-11e7-9ee6-d202ff485e06.png)

The sound is buggy, but other than that, I have not found any real issues with this game.

Shogun

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#351_

**Comment by ObiKKa** [comment]
[Proof video](https://www.youtube.com/watch?v=RQc7B8BsovQ) from Literalmente{Game} (Uploaded Oct 22, 2017. Build 853eea7b. [PR 764](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/764) - 11 days old).

**Comment by Margen67** [comment]
Will reopen once Xbe dump and KrnlDebug.txt are provided.
