### ISSUE TITLE
Area51 [Area 51] [4D570005]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#14]
[Wikipedia](https://en.wikipedia.org/wiki/Area_51_(first-person_shooter))

_From @fatjohnny118 on August 9, 2017 2:48_

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210189/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103104-a4115e14-7c8b-11e7-82f1-602508af75c8.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210191/KrnlDebug.txt)
xbe dump below
[Area51.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213259/Area51.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#652_

**Comment by BenNottelling** [comment]
From #233
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255830/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255831/KrnlDebug.txt)



videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Margen67** [comment]
Duplicate of #357.
