### ISSUE TITLE
And 1 StreetBall [AND 1 Streetball] [US-086] [1.02]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#15]
[Wikipedia](https://en.wikipedia.org/wiki/AND_1_Streetball)

_From @fatjohnny118 on August 9, 2017 2:47_

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210186/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103088-941131e2-7c8b-11e7-9597-9b6890902d52.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210187/KrnlDebug.txt)
xbe dump below
[And 1 StreetBall.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213257/And.1.StreetBall.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#651_

**Comment by Voxel9** [comment]
From #228 
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255777/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255778/KrnlDebug.txt)

videos uploaded after i upload all my logs

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Margen67** [comment]
Xbe dumps are needed in order to fix the issue title. I will reopen this once they are provided.

**Comment by Margen67** [comment]
No description, and doesn't use the issue template. I will reopen this issue if a new report is posted.
