### ISSUE TITLE
PSYVARIAR2 EXTEND EDITION [Psyvariar 2 - Extended Edition]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#166]
[Wikipedia](https://en.wikipedia.org/wiki/Psyvariar_2)

## Issues
* in-game with some errors

_From @furrya on March 26, 2017 0:8_

![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24327124/b00d148a-1203-11e7-838b-7e106fe8690f.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24327125/b00d6f98-1203-11e7-8417-42fa0450d30d.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24327123/b00ce960-1203-11e7-9c90-48346590072a.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/870471/KrnlDebug.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#279_

**Comment by PatrickvL** [comment]
_From @furrya on May 4, 2017 1:25_


 With Cxbx-Reloaded Version 36f9e171 (May  3 2017) dirty disk error has disappeared and  I can reach in-game. ~~But one note I need to mentioned - I get an error immediately if I press start on first intro screen - probably need wait a little and press start.~~  Fixed by @jarupxx at PR #443 
![screenshot_6](https://cloud.githubusercontent.com/assets/25540784/25687763/22dd88a4-30b4-11e7-981c-aec49609b948.png)
 ![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25687589/91f00a5c-30b2-11e7-8afe-8b184b37b7ba.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25687587/91eef270-30b2-11e7-80bd-d9f8fa790047.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25687588/91ef693a-30b2-11e7-91d2-dee64bb6dd0b.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25687590/91f09404-30b2-11e7-88b6-77ac9fd4aeed.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/25687591/91f2e0a6-30b2-11e7-8eb4-be20a39b644f.png)
______________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/975060/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
_From @jarupxx on May 5, 2017 21:14_

If I press start on first intro screen immediately, it seems that the unimplemented function ```IDirectSoundBuffer_Use3DVoiceData``` is called. This will work with PR #443.

**Comment by PatrickvL** [comment]
_From @furrya on May 6, 2017 3:13_

@jarupxx Great! I confirm that the error has disappeared.

**Comment by PatrickvL** [comment]
_From @furrya on May 6, 2017 3:16_

I have retested game emulation and now I can play about 3 - 4 minutes, before another error appears
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25769486/6ebe5ad0-3255-11e7-8d32-db14d9566989.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980656/KrnlDebug.txt)

**Comment by ObiKKa** [comment]
A huge update. A new [video](https://www.youtube.com/watch?v=SFaCGowuGvw) from Literalmente{Game} shows that this game can now run indefinitely. Uses a build ([92ef8a6](https://github.com/PatrickvL/Cxbx-Reloaded/commit/92ef8a649ac59b7aee43cbbe6b3df1597100feee)) from PatrickvL's WIP_LessVertexPatching branch. 

Description in English:
> Great improvement in this game that crash after the end of the battle with the first mid-boss. Now it's playable indefinitely (in my case, the emulator crashed for lack of RAM, and that's the sound you hear at the end of the video). The performance is inconsistent, so again I will not include the benchmark data for not reporting something inaccurate.

**Comment by Margen67** [comment]
Will reopen once Xbe dump and new KrnlDebug.txt are provided.
