### ISSUE TITLE
PSO [Phantasy Star Online: Episode I & II]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#171]
## Issues
- lack of textures and other graphics problems

_From @furrya on March 25, 2017 10:10_

Phantasy Star Online: Episode I & II - the game almost reached the menu and has two exception errors before I can start
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24321386/7046206e-118e-11e7-82d2-865d204f30c7.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24321385/70451a66-118e-11e7-886d-56d0a658311c.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/869914/KrnlDebug.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#274_

**Comment by PatrickvL** [comment]
_From @furrya on April 10, 2017 1:27_

With the 7760a7d (Apr 9 2017) build of Cxbx Reloaded, KeBugChek warning appears at the start , though I can skip some of them and get to the third intro screen
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24842860/e76e3f6e-1dd7-11e7-88c8-7c4c69c061cf.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/908739/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
_From @furrya on August 4, 2017 8:56_

CXBX - Reloaded Version 488db56077f776b2d6bb75382717c68bddabe8a5
The music in the menu is fully working now but the game crashes at a time when I  press a start button  ![screenshot_1](https://user-images.githubusercontent.com/25540784/28961371-002f9654-793d-11e7-8918-d7a5903cb420.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1199752/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
_From @RadWolfie on August 4, 2017 17:37_

Sound serious, I'll investigate what went wrong with DirectSoundBuffer creation.

**Comment by PatrickvL** [comment]
_From @furrya on August 6, 2017 3:32_

The game is now perfectly loaded. The music in the game is fully played, only the textures are missing and in the intro video half of the screen is not visible. Version is 9d8ae41e

![screenshot_1](https://user-images.githubusercontent.com/25540784/29000339-62e8421c-7aa2-11e7-8c15-c0581f6b49bc.png)
![screenshot_2](https://user-images.githubusercontent.com/25540784/29000340-62e9f864-7aa2-11e7-9111-e2f813d6c8ff.png)
![screenshot_3](https://user-images.githubusercontent.com/25540784/29000341-62eace6a-7aa2-11e7-9132-12e57d59ca18.png)
![screenshot_4](https://user-images.githubusercontent.com/25540784/29000342-62ed70a2-7aa2-11e7-9e0d-1bdb2caaa28a.png)
![screenshot_5](https://user-images.githubusercontent.com/25540784/29000343-62f0507e-7aa2-11e7-9b52-8874cb50ef8b.png)
![screenshot_6](https://user-images.githubusercontent.com/25540784/29000344-62f3d80c-7aa2-11e7-80ba-69ec0ea06323.png)
![screenshot_7](https://user-images.githubusercontent.com/25540784/29000345-63124e7c-7aa2-11e7-8fea-745831c8fb12.png)
![screenshot_8](https://user-images.githubusercontent.com/25540784/29000348-6318ce5a-7aa2-11e7-8130-0b8e3ea0e78a.png)
![screenshot_9](https://user-images.githubusercontent.com/25540784/29000346-63164dba-7aa2-11e7-830e-953ea76a104d.png)
![screenshot_10](https://user-images.githubusercontent.com/25540784/29000347-6316ecac-7aa2-11e7-8a35-71090e3364e0.png)
________________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202845/KrnlDebug.txt)

**Comment by furrya** [comment]
There is a regression now in Cxbx-Reloaded Version e4be8e87 (Aug 30 2017) when I try to start a New game from the menu 
![screenshot_2](https://user-images.githubusercontent.com/25540784/29904550-57d34dc6-8e44-11e7-9873-f0f8c371bdfb.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1265653/KrnlDebug.txt)

**Comment by LukeUsher** [comment]
That's irritating, the latest commits showed no regressions and even some improvements across the 40 games I've tested. I'll investigate

**Comment by jarupxx** [comment]
I compared the logs of Version 9d8ae41e and Version e4be8e87.
The following functions are add or modify.
```
Newly registered functions
0x00399980 -> D3DDevice_Begin
0x0039bc40 -> D3DDevice_IsBusy
0x00397a00 -> D3DDevice_SetRenderState_PSTextureModes
0x003992f0 -> D3DDevice_SetRenderState_SampleAlpha
0x003a142b -> D3D_CMiniport_GetDisplayCapabilities
0x003f8928 -> XMountMUA
0x003e2606 -> connect
0x003e2fa9 -> recv
0x003e3195 -> send
0x003e374f -> socket

Fixed location functions
0x003998e0 -> D3DDevice_SetVertexData2f
0x00399920 -> D3DDevice_SetVertexData4f
0x003e2582 -> bind
0x003e1900 -> ioctlsocket
```

**Comment by ObiKKa** [comment]
New video from InsertMoreCoinsblog IMC: [Cxbx (last build) - Phantasy Star Online I & II - Boots but hangs on start](https://www.youtube.com/watch?v=H2CNF5WkyDU) (Dec 6, 2017).

**Comment by Spartan304** [comment]
This title now gets in game with no graphical issues until you warp down to the planet.  Once there the map is centered on the screen and from what I can tell it will show the full map once you've explored the area.
![PSO 1 2](https://user-images.githubusercontent.com/5041078/67136665-5eba6200-f1f7-11e9-98ed-a87e66eeaeea.JPG)

A couple of audio issues: 
On loading screen is running the cursor only makes the "twinkle" sound when you begin to move it but then immediately stops.  
Doors on the planet don't make a sound.  
Fly spitter enemy, and bugs, don't produce their buzzing noise.

**Comment by Margen67** [comment]
@Spartan304 Please provide the KrnlDebug.txt and Xbe dump.
