### ISSUE TITLE
Miami Vice [?] [?]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#175]
## Issues
 - the game reaches the title screen, but controller does not work

_From @furrya on March 24, 2017 11:42_

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/867702/KrnlDebug.txt)
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24292837/51c70188-10d2-11e7-9eb6-f64022e4703b.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24292838/51c7541c-10d2-11e7-9aae-bf57371b5009.png)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#266_

**Comment by PatrickvL** [comment]
_From @furrya on April 30, 2017 3:28_

The game reaches the title screen now, but controller does not work 
_________________________________________________________________________
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25561132/179b7b0c-2da0-11e7-8abe-6059147dd2b0.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25561134/1d27c5bc-2da0-11e7-8706-80a51902e87b.png)
______________________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/966538/KrnlDebug.txt)

**Comment by ObiKKa** [comment]
Don Johnson with a see-through cross around his shoulders for the win! :sweat_smile: :stuck_out_tongue_winking_eye: :grinning: :grin: Though, his shoulder bands do shimmer in and out of existence, based on your perspective of his model.
But, man, this game sure does look drab. :disappointed: :scream_cat: :poop: :hurtrealbad:

- [Cxbx-Reloaded Xbox Emulator - Miami Vice Ingame! (3c201d7 + WIP / HW Mode, FXAA)](https://www.youtube.com/watch?v=igZLNbtCcGc&index=21&list=PL4PD8cV5ypNDPTJbrol7A-5rvuteHWWYj&t=1s) (Mar 6, 2018. John GodGames Emus. Build came just before Luke's vblank timing fix, though has his QueryPerformanceCounter fix; but the timing here is good. Screen is stretched widescreen.)
- [Emulação - Miami Vice in-game no CxBx-Reloaded (emulador de XBox)](https://www.youtube.com/watch?v=_HphnSdnBbw) (Build: [PR#968](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/bf0e2fe8f0b18cfe4c022dedb8d3da4fec92021b); unfortunately just before Luke's QueryPerformanceCounter and vblank timing fixes. So the timing here is too fast. Screen is not stretched, so it looks natural.)

**Comment by Margen67** [comment]
No way of identifying the reported game. Closing.
