### ISSUE TITLE
MARVEL VS. CAPCOM2 [Marvel vs. Capcom 2] [43430007]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#182]
## Issues
 - Missing HLE patch

_From @UlsterRose on March 15, 2017 22:4_

`[0x1C74] EmuWarn: EmuX86_Write32(0xFD714178, 0x0F39F518) Unexpected NV2A access, missing a HLE patch. Please notify https://github.com/Cxbx-Reloaded/Cxbx-Reloaded which title raised this!`

This line gets spammed in the console, albeit with varying addresses.

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/846120/KrnlDebug.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#237_

**Comment by PatrickvL** [comment]
The debug log doesn't show all details, so it's hard to tell, but it seems like this is an LTCG title

**Comment by PatrickvL** [comment]
_From @jarupxx on March 19, 2017 9:19_

I found it from the dxbx compatibility list. This title using non-LTCG version 5028.

**Comment by PatrickvL** [comment]
_From @jarupxx on March 24, 2017 12:34_

@DisorderIy I maked HLE Patch for this game. I am pleased if you can test it https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/267 .

**Comment by PatrickvL** [comment]
_From @UlsterRose on March 24, 2017 16:26_

The game now crashes after this gets printed to the console:
`[0x15A8] EmuWarn: SetRenderTarget Failed! (0x8876086C)`

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/868497/KrnlDebug.txt)

**Comment by Eurose209** [comment]
![image](https://user-images.githubusercontent.com/8225831/40284232-e02f0b0c-5c83-11e8-9414-4875a9d166c0.png)

Not sure since when, but this game is playable, albeit with slightly buggy graphics and broken character voices.

**Comment by mr975** [comment]
One of the best.games ever

**Comment by Margen67** [comment]
@escape209 Please provide the KrnlDebug.txt and Xbe dump.

**Comment by legolas119** [comment]
i'm using the latest cxbx version, the character select screen isn't visible and there are a lot of graphical glitches during the game. Is it normal or is it possible to solve these issues?

**Comment by Margen67** [comment]
@legolas119 This repository isn't for tech support.
File a new game-compatibility issue since this one is useless.
