### ISSUE TITLE
All-Star Baseball '04 [All-Star Baseball 2004] [AC-024] [1.01]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#21]
[Wikipedia](https://en.wikipedia.org/wiki/All-Star_Baseball_2004)

_From @fatjohnny118 on August 9, 2017 2:44_

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210171/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103003-1110b1a0-7c8b-11e7-9874-7740bcc770f6.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210172/KrnlDebug.txt)
xbe dump below
[All-Star Baseball '04.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213248/All-Star.Baseball.04.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#645_

**Comment by BenNottelling** [comment]
Latest logs from #222
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255695/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255696/KrnlDebug.txt)

**Comment by Margen67** [comment]
No description, and doesn't use the issue template. I will reopen this issue if a new report is posted.
