### ISSUE TITLE
AFL LIVE 2004

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#213]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255581/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255582/KrnlDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment]
Duplicate of #29

**Comment by BenNottelling** [comment]
Commented info on #29, remember to keep these all in one issue!
