### ISSUE TITLE
Animaniacs: TGEH [Animaniacs: The Great Edgar Hunt] [CM-003] [1.01]

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#229]
[Wikipedia](https://en.wikipedia.org/wiki/Animaniacs%3A_The_Great_Edgar_Hunt)

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258065/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255791/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255792/KrnlDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Margen67** [comment]
No description, and doesn't use the issue template. I will reopen this issue if a new report is posted.
