### ISSUE TITLE
ATV3 Release

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#237]
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258058/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255844/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255845/KrnlDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment]
The region on this XBE appears to be 0x80000007. Make sure this is actually a valid XBE please

**Comment by LukeUsher** [comment]
0x80000000 is the manufacturing region flag, xbes with this are designed to be ran in the factory environment. It is unlikely that any retail games had this flag, based on this, and the fact the media flag of includes the chihiro, HDD, and even DVD-RW flags, it's safe to assume that this is a pirated executable with region and anti-piracy patches applied. This makes it unusable for bug reports as we have no idea how else it could have been modified. Closing.
