### ISSUE TITLE
AIRFORCE DELTA II [Airforce Delta Storm] [KN-002] [1.01]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#24]
[Wikipedia](https://en.wikipedia.org/wiki/AirForce_Delta_Storm)

_From @fatjohnny118 on August 9, 2017 2:41_

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210141/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102700-f8bb5de6-7c88-11e7-9d25-cce1b465de86.PNG">
[krnldebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210162/krnldebug.txt)
xbe dump below
[AIRFORCE DELTA II.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213233/AIRFORCE.DELTA.II.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#642_

**Comment by BenNottelling** [comment]
Latest logs from #218
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255619/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255624/KrnlDebug.txt)

**Comment by Margen67** [comment]
No description, and doesn't use the issue template. I will reopen this issue if a new report is posted.
