### ISSUE TITLE
bad boys 2

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#241]
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258053/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255881/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255882/KrnlDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by ergo720** [comment]
The xbe dump identifies this title as "xmenu", it doesn't seem to be the game of the title...

**Comment by LukeUsher** [comment]
In addition to this, the region flag and media flags have the debug bit set, meaning that either this is not an official release, or is pirated content, which we cannot support.
