### ISSUE TITLE
BIONICLE® [EA-057] [1.01]

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#259]
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258022/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255999/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256001/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256000/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256002/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256003/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256004/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256005/PSDef004.txt)
[PSDef005.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256006/PSDef005.txt)
[PSDef006.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256007/PSDef006.txt)
[PSDef007.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256008/PSDef007.txt)
[PSDef008.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256009/PSDef008.txt)
[PSDef009.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256012/PSDef009.txt)
[PSDef010.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256010/PSDef010.txt)
[PSDef011.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256011/PSDef011.txt)
[PSDef012.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256013/PSDef012.txt)
[PSDef013.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256014/PSDef013.txt)
[PSDef014.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256015/PSDef014.txt)
[PSDef015.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256016/PSDef015.txt)
[PSDef016.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256017/PSDef016.txt)
[PSDef017.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256018/PSDef017.txt)
[PSDef018.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256019/PSDef018.txt)
[PSDef019.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256020/PSDef019.txt)
[PSDef020.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256023/PSDef020.txt)
[PSDef021.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256021/PSDef021.txt)
[PSDef022.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256022/PSDef022.txt)
[PSDef023.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256024/PSDef023.txt)
[PSDef024.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256025/PSDef024.txt)
[PSDef025.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256026/PSDef025.txt)
[PSDef026.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256027/PSDef026.txt)
[PSDef027.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256028/PSDef027.txt)
[PSDef028.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256029/PSDef028.txt)
[PSDef029.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256030/PSDef029.txt)
[PSDef030.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256031/PSDef030.txt)
[PSDef031.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256032/PSDef031.txt)
[PSDef032.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256033/PSDef032.txt)
[PSDef033.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256034/PSDef033.txt)
[PSDef034.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256035/PSDef034.txt)
[PSDef035.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256036/PSDef035.txt)
[PSDef036.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256037/PSDef036.txt)
[PSDef037.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256038/PSDef037.txt)
[PSDef038.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256039/PSDef038.txt)
[PSDef039.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256040/PSDef039.txt)
[PSDef040.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256041/PSDef040.txt)
[PSDef041.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256042/PSDef041.txt)
[PSDef042.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256043/PSDef042.txt)
[PSDef043.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256044/PSDef043.txt)
[PSDef044.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256045/PSDef044.txt)
[PSDef045.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256046/PSDef045.txt)
[PSDef046.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256047/PSDef046.txt)
[PSDef047.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256048/PSDef047.txt)
[PSDef048.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256049/PSDef048.txt)
[PSDef049.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256050/PSDef049.txt)
[PSDef050.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256051/PSDef050.txt)
[PSDef051.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256052/PSDef051.txt)
[PSDef052.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256053/PSDef052.txt)
[PSDef053.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256054/PSDef053.txt)
[PSDef054.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256055/PSDef054.txt)
[PSDef055.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256056/PSDef055.txt)
[PSDef056.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256057/PSDef056.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Margen67** [comment]
No description, and doesn't use the issue template. I will reopen this issue if a new report is posted.
