### ISSUE TITLE
After Burner II [after burner ll arcade] [MS-050] [1.01]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#26]
[Wikipedia](https://en.wikipedia.org/wiki/Shenmue_II)

_From @fatjohnny118 on August 9, 2017 2:28_

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210135/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102682-d6468862-7c88-11e7-813c-12247d00c76b.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210136/KrnlDebug.txt)
xbe dump below
[after burner ll arcade.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213230/after.burner.ll.arcade.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#640_

**Comment by BenNottelling** [comment]
Latest logs from #216
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255610/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255611/KrnlDebug.txt)

**Comment by Margen67** [comment]
No description, and doesn't use the issue template. I will reopen this issue if a new report is posted.
