### ISSUE TITLE
AFL Premiership [AFL Premiership 2005] [54510101]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#27]
[Wikipedia](https://en.wikipedia.org/wiki/AFL_Premiership_2005)

_From @fatjohnny118 on August 9, 2017 2:27_

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210132/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102667-c18c4eac-7c88-11e7-94cd-3669c931f740.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210133/KrnlDebug.txt)
xbe dump below
[afl premiumship.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213228/afl.premiumship.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#639_

**Comment by BenNottelling** [comment]
From #215
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255597/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255599/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255600/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255601/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255602/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255604/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255605/PSDef004.txt)
[PSDef005.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255603/PSDef005.txt)
[PSDef006.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255606/PSDef006.txt)
[PSDef007.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255607/PSDef007.txt)


videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Margen67** [comment]
No proper description, much like fatjohnny118's other issues..
