### ISSUE TITLE
BPS Trophy Bass 2007 [Bass Pro Shops: Trophy Bass 2007] [VU-073] [v1.01]

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#273]
### Description

LTCG title, unsupported.

### Dumps 

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1257989/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256144/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256145/KrnlDebug.txt)

### Status
**Previous behavior:**

**Current behavior:**
Shows LTCG title error message

**Comment by FerPozzetti** [comment]
Version f1d09af (Jun  8 2020)

Boots, then freezes at loading screen.

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4785597/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4785598/Xbe.txt)

![1o](https://user-images.githubusercontent.com/56910468/84755434-09a63a00-af98-11ea-9273-bbbe51b8b92c.jpg)
![2](https://user-images.githubusercontent.com/56910468/84755452-0ca12a80-af98-11ea-99db-f95603064b06.jpg)

**Comment by Margen67** [comment]
No description, and doesn't use the issue template. I will reopen this issue if a new report is posted.
