### ISSUE TITLE
BUFFY VAMPIRE SLAYER

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#281]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256210/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256211/KrnlDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by ergo720** [comment]
Duplicate of #181

**Comment by LukeUsher** [comment]
Please stop creating issues for titles that are already listed in the compatibility database. There is a strict rule of one issue per game, as this issue tracker is meant to serve as a compatibility list.
