### ISSUE TITLE
Championship Manager 5 [ES-026] [v1.08]

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#291]
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1257960/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256390/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256391/KrnlDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Margen67** [comment]
No description, and doesn't use the issue template. I will reopen this issue if a new report is posted.
