### ISSUE TITLE
Club Football 2005 [Club Football 2005 ASTON VILLA] [CM-051] [1.01]

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#303]
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258076/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258078/KrnlDebug.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258079/CxbxDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Margen67** [comment]
No description, and doesn't use template. I will reopen this issue if a new report is posted.
