### ISSUE TITLE
Club Football 2005 [Club Football 2005 BVB 09] [CM-063] [1.01]

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#305]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258088/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258089/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258090/Xbe.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Margen67** [comment]
New xbe dumps are needed in order to fix the issue title. I will reopen this once they are provided.
