### ISSUE TITLE
Club Football 2005 - CELTIC [CM-053] [v1.01]

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#306]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258092/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258093/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258094/Xbe.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Margen67** [comment]
No description, and doesn't use template. I will reopen this issue if a new report is posted.
