### ISSUE TITLE
Club Football - Inter Milan [CM-027] [1.01]

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#308]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258100/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258101/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258102/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258103/PSDef001.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258104/Xbe.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Margen67** [comment]
No description, and doesn't use template. I will reopen this issue if a new report is posted.
