### ISSUE TITLE
TimeSplitters 2 PAL

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#313]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258214/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258215/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258216/Xbe.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by ergo720** [comment]
Duplicate of #8

**Comment by Margen67** [comment]
This is a different version than #8, but I will keep this closed until a proper report is posted here.
