### ISSUE TITLE
Agressive inline [41430007]

### ISSUE THREAD

**Issue by GeeseHoward** [Cxbx-Reloaded/game-compatibility#330]
![capture2](https://user-images.githubusercontent.com/31681252/30094528-35abb88e-9310-11e7-87fc-c5cdb67c6b19.PNG)

### Description

Game instantly displays this error message

### Status
**Previous behavior:**

**Current behavior:**

**Comment by BenNottelling** [comment]
First: the shows us nothing, if it's an LTCG title it can't be emulated without LLE enabled
Second: there are no dumps here so even if it wasn't LTCG it would still be useless
Third: there is no XBE dump, where did you get this title ID? (41430007)

**Comment by literalmente-game** [comment]
Duplicate of https://github.com/Cxbx-Reloaded/game-compatibility/issues/25

**Comment by CakeLancelot** [comment]
As @literalmente-game said this is a duplicate, though the previous issue wasn't entirely accurate (should be state-unsupported because of LTCG). Therefore I've updated the previous issue and will be closing this one.
