### ISSUE TITLE
Crash Bandicoot: The Wrath of Cortex [52410006,56550003,56560001]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#4]
[Wikipedia](https://en.wikipedia.org/wiki/Crash_Bandicoot:_The_Wrath_of_Cortex)

_From @saq123 on August 11, 2017 1:30_

Every time I run the .XBE file or the logo does not appear! Only one black screen

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#662_

**Comment by PatrickvL** [comment]
_From @literalmente-game on August 11, 2017 1:42_

As Cxbx-Reloaded is in early stages of development right now, most games will either crash or do nothing. Please do not submit issues for these games.

Please report games that actually do something. If a game outputs graphics or audio before crashing, please submit a bug report at GitHub containing the build tested with, error message displayed (if any), screenshots, an Xbe dump (created via [Edit -> Dump Xbe Info To -> File]), and a Kernel Debug file (created when running a game when [View -> Debug Output (Kernel) -> File]) is selected.

**Comment by PatrickvL** [comment]
_From @saq123 on August 11, 2017 14:46_

oh,sorry.

**Comment by BenNottelling** [comment]
@saq123 please add the info we are looking as a comment, without everything Patrick mentioned this won't help!

**Comment by PatrickvL** [comment]
Duplicate of #162

**Comment by saq123** [comment]
the more I've seen people with old builds that came up with some result,
the intro at least.

2017-08-22 8:34 GMT-03:00 PatrickvL <notifications@github.com>:
