### ISSUE TITLE
All XBLA games on original Xbox system

### ISSUE THREAD

**Issue by ObiKKa** [Cxbx-Reloaded/game-compatibility#420]
This is not a specific game issue but instead meant to be a list of all of the downloadable Xbox Live Arcade (XBLA) games that ever appeared on the original Xbox game console. Perhaps the admins will be happy with this as it would help to refer people through links to the relevant game issue pages for the various XBLA games. It's also **FAR** easier to search for this page first and then redirect to a suitable game issue link.

1) Lots of details about the XBLA games at this [Wikipedia page](https://en.wikipedia.org/wiki/Xbox_Live_Arcade).
2) [[Xbox] Xbox LIVE Arcade Games](https://www.youtube.com/playlist?list=PLutMxePtcpooOj6XB9-NnAY4f3ZHWt0s7) playlist showcasing the XBLA games menu and all 27 games (Videos made in 2013. Playlist last updated on Sep 13, 2016.)
3) This [August 2012 user-created forum thread](https://www.xbmc4xbox.org.uk/forum/viewtopic.php?f=12&t=260) enquired about knowing all the XBLA titles that came online on original Xbox. Thus the list of all of these XBLA titles is populated down below here:

- [Alien Sky](https://github.com/Cxbx-Reloaded/game-compatibility/issues/134#issuecomment-338493592)
- AstroPop
- Atomaders
- Bankshot Billiards
- [Bejeweled](https://github.com/Cxbx-Reloaded/game-compatibility/issues/135)
- [Bookworm](https://github.com/Cxbx-Reloaded/game-compatibility/issues/134)
- Dangerous Mines
- [Dino and Aliens](https://github.com/Cxbx-Reloaded/game-compatibility/issues/134#issuecomment-338493592)
- Feeding Frenzy
- Fuzzee Fever
- Gauntlet (Part of the [Midway Arcade Treasures](https://github.com/Cxbx-Reloaded/game-compatibility/issues/50) pack)
- Guardian
- [Hamsterball (Gold)](https://github.com/Cxbx-Reloaded/game-compatibility/issues/134#issuecomment-338493592)
- Hardwood Solitaire
- Joust (Part of the [Midway Arcade Treasures](https://github.com/Cxbx-Reloaded/game-compatibility/issues/50) pack)
- Marble Blast Gold
- Ms. Pac-Man
- Mutant Storm
- Namco Vintage (Contains Pole Position, Dig Dug, & Galaga)
- Orbz
- Pipeline
- Ricochet Lost Worlds
- Robotron: 2084 (Part of the [Midway Arcade Treasures](https://github.com/Cxbx-Reloaded/game-compatibility/issues/50) pack)
- Smash TV (Part of the [Midway Arcade Treasures](https://github.com/Cxbx-Reloaded/game-compatibility/issues/50) pack)
- [Super Collapse II](https://github.com/Cxbx-Reloaded/game-compatibility/issues/133)
- Think Tanks
- Zuma

An admin can take over from here, re-organize as desired. But I and others can also edit such as adding links to new issue pages for these games.

Games that have their own issues: 10.
Games that still don't have their own issues: 17 remaining.

**Comment by CakeLancelot** [comment]
This list is kind of breaking the whole '1 game 1 issue' rule but until each title has it's own issue this should be useful. Perhaps we should have a 'type-xbla' label as well?

**Comment by RadWolfie** [comment]
I agree with @CakeLancelot. Instead of making an issue with list of XBLA titles, it would be better put this information in a wiki page?

And yes, we should have 'type-XBLA' label for each XBLA title's issue for easy tracking list from issue search.

**Comment by CakeLancelot** [comment]
> Instead of making an issue with list of XBLA titles, it would be better put this information in a wiki page?

This sounds like a good idea, though I already created a [redirect](https://github.com/Cxbx-Reloaded/game-compatibility/wiki) from this repository's wiki to the main one. 

Which I think makes sense but to reduce clutter it may be a good idea to categorize the wiki pages, perhaps technical inner-workings of the emulator and game-related pages? So as we create more pages there is a clear distinction of who the information is meant for (developer, user, or both).

**Comment by RadWolfie** [comment]
Wiki for game compatibility repo should serve purpose for games relative to retail, xbla, and homebrew. Cxbx's own Wiki is for internal purpose only. We want to keep both separately as possible. If that is what you're saying.

I don't think compatibility's Wiki need numerous of pages. Maybe just 3 or 4?

**Comment by CakeLancelot** [comment]
> We want to keep both separately as possible. If that is what you're saying.

Originally I wanted for just one wiki with different categories to avoid confusion - but I suppose keeping two separate ones wouldn't be a problem. However where would you think a guide for say dumping games or using the emulator would belong - the main wiki or game compatibility?

**Comment by RadWolfie** [comment]
Github's Wiki doesn't have different categories support. Plus the design is not really that great.

Cxbx has nothing to do with dumping games itself. I would say game compatibility's wiki is the best place to put detail how to dump retail games properly.

**Comment by PatrickvL** [comment]
There already is a "type-xbla" label.


I agree that the xbla list itself should be put in a wiki page of the game-compatibility project. This list should at least link each xbla title to the corresponding xbla title-specific issue on github.


As for adding information about how to dump a disc - isn't that documented all over the internet already? For example, XboxDevWiki probably already contains something written on the matter.

No need to reinvent the wheel.
Plus, it would be a little safer legal-wise to avoid the subject altogether. Call me over-cautions, but I really don't want to receive a "cease and desist" letter over of such a triviality...

**Comment by CakeLancelot** [comment]
> There already is a "type-xbla" label.

I added it recently, but the README has not been updated. I'll try to update it when I can (should also have type-coverdisc, and type-chihiro)


> No need to reinvent the wheel.

That's reasonable, we should probably move this issue page to a wiki page though.@ObiKKa would it be okay if I were to copy this issue into a new wiki page? If you want to make/propose the changes yourself that's fine as well.

**Comment by CakeLancelot** [comment]
> An admin can take over from here, re-organize as desired.

Didn't see this bit. I've gone ahead and [moved this to a wiki page](https://github.com/Cxbx-Reloaded/game-compatibility/wiki/XBLA-Games-List) - please confirm that you have permissions to edit. Closing this issue - reopen and/or comment on this if there's any issue with the wiki page.

**Comment by ObiKKa** [comment]
Thanks, CakeLancelot for redirecting this issue over to a new Wiki page. I didn't know of that Wiki tab before I created this issue but now I do. I'll edit over there further as the links are a bit unclear (3 games still don't have their own issues yet but I previously linked them to another game's issue page. Also some other games are available in 2 ways or might be different versions but of the same titles.).

**Comment by Margen67** [comment]
I've moved the list of XBLA games to a project: https://github.com/Cxbx-Reloaded/game-compatibility/projects/2
Further discussion belongs on the [Discord](https://discord.gg/26Xjx23).
