### ISSUE TITLE
Shikigami no Shiro [式神の城] [MP-002] [1.01]

### ISSUE THREAD

**Issue by darkstar** [Cxbx-Reloaded/game-compatibility#468]
[Shikigami no Shiro](https://en.wikipedia.org/wiki/Shikigami_no_Shiro)

### Description

Game crashes during load.

### Dumps 

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1597385/KrnlDebug.txt)

[____-96706740.ini
](https://github.com/Cxbx-Reloaded/game-compatibility/files/1597389/____-96706740.ini.txt)

[crashdumps.zip](https://github.com/Cxbx-Reloaded/game-compatibility/files/1597394/crashdumps.zip)

### Status
**Previous behavior:** 

None reported

**Current behavior:**

Crash

### Additional Information

Tested with build 984e2bd5

**Comment by LukeUsher** [comment]
Interesting that no Direct3D symbols were detected, never seen that happen with a non LTCG title before.

Could you clear your HLE Cache [Settings => HLE Cache => Clear entire HLE Cache" and upload a new KrnlDebug log? The current log you uploaded shows reading from the HLECache, but it would be helpful to get a log containing the actual symbol scanning.

Thanks,
Luke

**Comment by LukeUsher** [comment]
Disregard the above, I just noticed you have LLE_GPU enabled! This feature does quite work yet, so any test-results with this feature enabled are invalid, please go to "Settings => LLE (Experimental) -> LLE GPU" and make sure that is is unticked and try again.

**Comment by darkstar** [comment]
How to determine whether this is an LTCG title or not? Is there some line in the log to look for?

I disabled LLE GPU (didn't even notice it was on, sorry) but the game still crashes.

Updated log:
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1597442/KrnlDebug.txt)

**Comment by LukeUsher** [comment]
Cxbx-Reloaded will try to warn you if it's an LTCG title, but it doesn't always work.

You can identify manually by checking for certain libraries linked in the Xbe, for example, if D3D8LTCG is present, it is an LTCG title.

**Comment by ObiKKa** [comment]
@LukeUsher. "does **not** quite work yet". Edit your message then someone (or I'll do it) delete this message.

**Comment by donwayo** [comment]
Adding [XbeInfo.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1781601/XbeInfo.txt) from xbox-db.herokuapp.com

**Comment by Margen67** [comment]
No xbe dump in the OP so this issue is useless.
