### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by jackbmh** [Cxbx-Reloaded/game-compatibility#477]
DELETED

**Comment by jackbmh** [comment]
It was a game report but I couldn't figure out how to add labels

**Comment by Voxel9** [comment]
You can't add labels as a regular user. Only members of the game compatibility repo can do that, such as me.
Feel free to make a new issue, and I'll add the labels for you. :)

**Comment by jackbmh** [comment]
Will do

**Comment by Margen67** [comment]
#478
