### ISSUE TITLE
Star Wars Battlefront II DVD Demo [LA-32795] [1.01]

### ISSUE THREAD

**Issue by jackbmh** [Cxbx-Reloaded/game-compatibility#478]
### Description
When file is selected, it says Star Wars Battlefront II DVD Demo at the top of the emulator window, but when emulation is started it says "Failed Xbox Live Update. Make sure disc isn't dirty or damaged"

### Status
Previous behavior:
Failed to emulate.

#### Current behavior:
Partially fails to emulate.
Says "Failed Xbox Live Update. Make sure disc isn't dirty or damaged"

[Xbe1.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2381429/Xbe1.txt)

### Additional Information:
XBE file has been copied from the "Revenge of the Sith" 2nd DVD. This is the Xbox demo. I have tried running The dashboard update XBE and the update XBE itself and still no change. Tested with the October 13, 2018 build.

**Comment by PatrickvL** [comment]
The Xbe might need media files to be copied along with it

**Comment by jackbmh** [comment]
I will add a dump now

**Comment by jackbmh** [comment]
What media files could be copied? The contents of the disc are default.xbe (the demo), dashupdate.xbe (dashboard update), ep3.dxr, a folder called "VIDEO_TS", a setup information file called "AUTORUN", and an application called "start"

**Comment by PatrickvL** [comment]
Running a debug build of Cxbx-Reloaded with kernel logging to file enabled, produces a trace of which files are attempted to access. This might give a clue

**Comment by jackbmh** [comment]
Where might I find a build like that?

**Comment by jackbmh** [comment]
Is it the "trace" build?

**Comment by PatrickvL** [comment]
https://ci.appveyor.com/project/SoullessSentinel/cxbx-reloaded/branch/master/job/efxk30l7bemqi5d5/artifacts

**Comment by jackbmh** [comment]
I have downloaded the file and extracted it, but when I try to run Cxbx, it tells me to download all of these DLL files and once I have completed that, it tells me that the application won't run.

**Comment by jackbmh** [comment]
I just tested this xbe with the build that came out yesterday (the release not the debug), and it gave me a message that said "Recieved Exception Code 0xC0000005 @ EIP := 0x0001B82D(=CreateMutexA_UNPATCHED+0x2a1e)" I had the option to debug it, so I did. Dump will be updated shortly.

**Comment by jackbmh** [comment]
I will now add a kernel debug

**Comment by Margen67** [comment]
The KrnlDebug was lost in a botched edit by the OP, and I'm not sure if it applies, so I'm closing this in favor of #858.
