### ISSUE TITLE
Digimon Battle Chronicle [Digimon Rumble Arena 2 JP] [BA-001] [1.01]

### ISSUE THREAD

**Issue by jeltaqq** [Cxbx-Reloaded/game-compatibility#490]
### Dumps 
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1608422/Xbe.txt)

#### Previous behavior:
None reported

#### Current behavior:
state-interactive

### Screenshots
![title](https://user-images.githubusercontent.com/25340049/34635665-3cdfccbe-f2d6-11e7-8390-eb74b8920d63.jpg)
![menu](https://user-images.githubusercontent.com/25340049/34635667-3f93442c-f2d6-11e7-959b-e26ef174e800.jpg)

### Additional Information
Tested with build Cxbx-Reloaded/Cxbx-Reloaded@1cc0220b

**Comment by ObiKKa** [comment]
The NA/PAL version gets in-game. Shows OK 3D menus with slight corruption. Gets in-game with incomplete GFX but hangs soon after with an external error message.

`Exception Code 0x0000005 @ EIP := 0x6F646AF8`

- [Cxbx-Reloaded Xbox Emulator - Digimon Rumble Arena 2 Ingame! (4ed8bce1)](https://www.youtube.com/watch?v=V0OHhC82xKg&t=0s&list=PL4PD8cV5ypNDPTJbrol7A-5rvuteHWWYj&index=26) (John GodGames Emus. Published on Feb 28, 2018.)

**Comment by Margen67** [comment]
OP has no description, and no KrnlDebug has been posted, so I will reopen this once someone has made a proper report.
