### ISSUE TITLE
Blood Wake [4D530010] 

### ISSUE THREAD

**Issue by ahmadsarvmeily** [Cxbx-Reloaded/game-compatibility#524]
### Description

The game boots with major graphical/audio issues, goes into menus but does not go in-game.

```
---------------------------
Cxbx-Reloaded
---------------------------
Received Exception Code 0xC0000005 @ EIP := 0x0FA36E40

  Press "OK" to terminate emulation.
  Press "Cancel" to debug.
---------------------------
OK   Cancel   
---------------------------
```

### Dumps 

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1626161/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1626162/KrnlDebug.txt)

### Status
**Previous behavior:** 

None reported

**Current behavior:**

Major graphical issues, broken audio, goes into menus, not in-game.

### Screenshots 
![image](https://user-images.githubusercontent.com/22861179/34877346-940907fa-f79d-11e7-821c-8c575d8f3bd4.png)

![image](https://user-images.githubusercontent.com/22861179/34877355-9e5456a6-f79d-11e7-8703-68b77edc1c62.png)

![image](https://user-images.githubusercontent.com/22861179/34877377-b4463a74-f79d-11e7-974b-960b4cdc364f.png)

**Comment by CakeLancelot** [comment]
I've moved any relevant info to #185, closing this one as a duplicate.

**Comment by Shideravan** [comment]
![image](https://user-images.githubusercontent.com/12163923/40264353-f00117a6-5af7-11e8-809d-8b5856ca9efe.png)
