### ISSUE TITLE
Riddick [The Chronicles of Riddick: Escape from Butcher Bay] [56550026]

### ISSUE THREAD

**Issue by hotzenplotz3000** [Cxbx-Reloaded/game-compatibility#677]
[The Chronicles of Riddick: Escape from Butcher Bay](https://en.wikipedia.org/wiki/The_Chronicles_of_Riddick:_Escape_from_Butcher_Bay)

### Description

PAL release
LTCG Title, not supported

### Dumps 
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1738235/Xbe.txt)

### Status
**Previous behavior:** 
None reported

**Current behavior:**
unsupported LTCG Title

### Screenshots 
None

### Additional Information
None

**Comment by bryce13950** [comment]
Duplicate? https://github.com/Cxbx-Reloaded/game-compatibility/issues/295
