### ISSUE TITLE
jet set radio little speed problem

### ISSUE THREAD

**Issue by equipeXomega117** [Cxbx-Reloaded/game-compatibility#687]
hello,
i have a little problem with jet set radio future :/ 
I run the game all is well but the game is accelerated speed I ran through the map in a few seconds ^^ it is not that I who is in accelere it is all the game (environment, character, time ect .. .)
in any case very nice job for this beautiful emulator :)
if there are mistakes I'm sorry but I'm not very strong in English: /

**Comment by CakeLancelot** [comment]
Try enabling Vsync in Video options, it should limit the framerate to where it doesn't run too fast.

**Comment by PatrickvL** [comment]
This issue tracker is not meant for support questions. Thanks for your appreciating though!
