### ISSUE TITLE
Fuzion Frenzy [4D530002] NTSC Version

### ISSUE THREAD

**Issue by defy190383** [Cxbx-Reloaded/game-compatibility#695]
### Description
Game boots and plays intro music while a black - green screen flashes periodically. When the main menu appears only black and letter green color, you can press start and after that a black screen loads.
Note: Apparently cyclized and overflow.

### Dumps 
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1787497/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1787498/Xbe.txt)

### Status
**Previous behavior:** 

**Current behavior:**
 

### Screenshots 
![ffrenzy](https://user-images.githubusercontent.com/37089032/37069869-e05587b2-217a-11e8-8c89-cb852ffd8f0f.png)

### Additional Information
With the difference that the PAL version shows the correct main menu.

**Comment by CakeLancelot** [comment]
The NTSC version should already be posted here: https://github.com/Cxbx-Reloaded/game-compatibility/issues/598. Please append your report to this issue instead.
