### ISSUE TITLE
JSRF - 0xC000005 @ EIP := 0x0005f500(unknown+0x0)

### ISSUE THREAD

**Issue by M0DULU5** [Cxbx-Reloaded/game-compatibility#697]
### Description

The Current version of the emulator causes an error message upon startup of the emulation

```
---------------------------
Cxbx-Reloaded
---------------------------
Received Exception Code 0xC0000005 @ EIP := 0x0005F500(=unknown+0x0)

  Press "OK" to terminate emulation.
  Press "Cancel" to debug.
---------------------------
OK   Cancel   
---------------------------

```

### Dumps 

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1805261/Xbe.txt)

### Status
**Previous behavior:** 

I tested with an earlier version and everything was running fine, unfortunately the earlier versions also rendered it unplayable past the title screen.

**Current behavior:**

Current version appears to not cooperate while older versions do, would like to find out if it's my end or not.

### Screenshots 

https://gyazo.com/c509518c00c0a46e83745eaf5088b429

**Comment by CakeLancelot** [comment]
This error usually has to do with older versions corrupting files. Go ahead and delete the AppData folder that Cxbx-Reloaded creates (type %appdata% into the start menu and look for Cxbx-Reloaded) and try again.

If you encounter issues still, report it in the respective issue: [PAL](https://github.com/Cxbx-Reloaded/game-compatibility/issues/178), [NTSC](https://github.com/Cxbx-Reloaded/game-compatibility/issues/409)

**Comment by HyperScorpio** [comment]
The issues still the same, even only add the save folder of the game.

**Comment by CakeLancelot** [comment]
@HyperScorpio Are you sure this the same problem? From your other posts in the JSRF issues you're able to get in-game just fine. The crash after the Hayashi boss battle will be looked into eventually, but there are other more important issues for the developers to look into first.

**Comment by HyperScorpio** [comment]
@CakeLancelot  Yes it is, i just wanna inform you, because is not fixed yet. I understand if the developers are working hard so much to make this working thing happen. We know other games need to be fixed and find those errors to make everything working. Thanks. 👍
