### ISSUE TITLE
The King Of Fighters '94 Rebout

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#7]
[Wikipedia](https://en.wikipedia.org/wiki/The_King_of_Fighters_%2794)

_From @HyperScorpio on August 9, 2017 23:33_

![sem titulo](https://user-images.githubusercontent.com/30736913/29148137-88de9958-7d63-11e7-9d19-51c3673b443a.png)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#659_

**Comment by PatrickvL** [comment]
_From @BenNottelling on August 10, 2017 5:52_

As I already said here https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/614#issuecomment-320423571 tiles with this error often are LTCG..
This title is probably LTCG so we can't support it in Cxbx-Reloaded, this report is also missing a XBE dump, kernal debug, ect making it useless to us

**Comment by PatrickvL** [comment]
_From @HyperScorpio on August 10, 2017 13:34_

Now i get it. This errors are the same for the games are not yet added, sorry next time i will search for bugs ingame. Close this. Thanks!

**Comment by PatrickvL** [comment]
This seems to be an unreleased retail title.

**Comment by ObiKKa** [comment]
Hey, hang on. I have found this useful [Wikipedia guide](https://en.wikipedia.org/wiki/Category:Cancelled_Xbox_games) which may show all of the known unreleased/cancelled Xbox games. 109 titles so far.

**Comment by Margen67** [comment]
There's no way of identifying the game reported. Closing.
