### ISSUE TITLE
Jet Set Radio Future [PAL]: Game crash during Chapter 5 Boss Fight (Spoilers)

### ISSUE THREAD

**Issue by kazuos** [Cxbx-Reloaded/game-compatibility#701]
The game crashes consistently (I think it might be on the same frame) during a cutscene that happens after the third round of Death Ball, after defeating the boss. Also, DJ Professor K speaks a line in French beforehand, even though language is set to English - possibly related? The French line is a repeat of an English line said seconds before.

```
Received Exception Code 0xC0000005 @ EIP := 0x15DF3A70
```

### Dumps 

[XBE Dump (I hope this is the right thing)](https://1drv.ms/u/s!AsJR7GOqKqeXgu4F2ewBlsuEKgGtTg)

### Status
**Previous behavior:** 

None reported

**Current behavior:**

Game crashes consistently in Chapter Five boss fight against Rokakku Terror Drone.

### Screenshots 
![2018-03-18_12-09-06](https://user-images.githubusercontent.com/10604176/37570300-60cbbc66-2aab-11e8-80fb-15d5aa4ad2d5.png)
![2018-03-18_12-09-12](https://user-images.githubusercontent.com/10604176/37570305-73ec9f54-2aab-11e8-91c9-b615da0f5e5c.png)
![cxbx_2018-03-18_11-57-16](https://user-images.githubusercontent.com/10604176/37570309-7e91ae72-2aab-11e8-90d6-d103e915bcd4.png)
![cxbx_2018-03-18_11-57-16 error](https://user-images.githubusercontent.com/10604176/37570310-8104e502-2aab-11e8-9d0d-90a3196e7330.png)

### Additional Information

OS: Windows 10 64-bit
CXBX-Reloaded Version 3e35a803 (Mar 16 2018)
The other 7 hours and 48 minutes of gameplay had relatively few issues, besides graffiti not rendering and the menu sounds and voices being corrupted. The game remained perfectly playable to this point.
![image](https://user-images.githubusercontent.com/10604176/37570317-a564c1ec-2aab-11e8-90bf-00870355a4b0.png)

**Comment by CakeLancelot** [comment]
[This is a known issue that is currently being worked on](https://github.com/Cxbx-Reloaded/game-compatibility/issues/178#issuecomment-373999153). Since an issue for JSRF PAL already exists this will be closed.

**Comment by CakeLancelot** [comment]
Now fixed by https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1000. (Just in case you weren't following the main issue)

**Comment by Margen67** [comment]
OP literally uploaded the entire game 🤦‍♂️
