### ISSUE TITLE
Jet Set Radio Future

### ISSUE THREAD

**Issue by Winchester7314** [Cxbx-Reloaded/game-compatibility#706]
Description
So I have an odd problem currently. It seems to be present in basically all newer revisions. I get a 
"Received Exception Code 0xc0000005 @ EIP := 0x0005Fc20(=unknown+0x0)" 
Everytime I try to launch the game. I have tried multiple revisions, used both NTSC, PAL, and even used the Sega combo disc version. I have tried using a different PC and still the issue is present for me. Any help would be appreciated.

Dumps 
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1855715/CxbxDebug.txt)

Additional Information
It is unknown whether my PAL source is a true PAL or not, however the issue still seems to exist for NTSC being straight up unplayable.

**Comment by Voxel9** [comment]
Please report any issues with the combo disc here:
https://github.com/Cxbx-Reloaded/game-compatibility/issues/409
and any issues with the original version here:
https://github.com/Cxbx-Reloaded/game-compatibility/issues/703

Closing as duplicate.
