### ISSUE TITLE
Unable to open Jet Set Radio Future anymore

### ISSUE THREAD

**Issue by Gncd** [Cxbx-Reloaded/game-compatibility#712]
### Description

When trying to launch the game I only get a black screen, and when using software mode i get the following:

```
---------------------------
Cxbx-Reloaded
---------------------------
Received Fatal Message:

* IDirect3D8::CreateDevice failed

---------------------------
OK   
---------------------------

```

### Dumps 

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1866525/Xbe.txt)
[KrnlDebug software mode.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1866527/KrnlDebug.software.mode.txt)
[KrnlDebug hardware mode.zip](https://github.com/Cxbx-Reloaded/game-compatibility/files/1866528/KrnlDebug.hardware.mode.zip)

### Additional Information

Running the latest version (1st of April)
Cant remember which version worked before, but I think it was like one month or so ago.

**Comment by T02my** [comment]
I'm running this game in 25 march release version

**Comment by Voxel9** [comment]
Pretty much almost nothing will ever work with software mode. Best to always stick with hardware/HAL setting for this reason.

Please use the existing issues for JSRF here: https://github.com/Cxbx-Reloaded/game-compatibility/issues/703

Closing as duplicate.

**Comment by Gncd** [comment]
>AND when using software mode 
The game does not launch using hardware mode NOR in software mode.
If I understood correctly the issue you linked has nothing to do with the game not launching...

**Comment by Voxel9** [comment]
It's working fine for me... but what I am trying to say is, let's keep everything under one roof in a single issue, as per the issue guidelines:

```
Do not create duplicate issues (first, search if a title already has an issue).
Duplicate reports will be merged into one, duplicates will be closed.
```

I'm just doing my job.

**Comment by Voxel9** [comment]
Anyway, since this issue's closed as a duplicate, I guess I could still help. Have you tried clearing settings? If that fails, maybe try deleting the Cxbx folder in AppData and seeing if that might help.

**Comment by Gncd** [comment]
Yeah that did the trick, thanks.
