### ISSUE TITLE
SOULCALIBUR2 [Soul Calibur 2] [4e4d0003]

### ISSUE THREAD

**Issue by ESPPIRAL** [Cxbx-Reloaded/game-compatibility#718]
Game crash on startup,

[0x2A6C] WARN: Popup : Received Fatal Message:

* Unknown Transform State Type (1678096)

[SOULCALIBUR2KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1912358/SOULCALIBUR2KrnlDebug.txt)

![bandicam 2018-04-15 13-56-53-382](https://user-images.githubusercontent.com/29869781/38778145-dffd7fe6-40b4-11e8-983a-53ff23117124.png)

**Comment by Voxel9** [comment]
Could you please upload an Xbe.txt dump for this game? thanks

**Comment by ESPPIRAL** [comment]
[sc2Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1913118/sc2Xbe.txt)

**Comment by dreimer1986** [comment]
[0x1BE0] WARN : PMEM    Out of physical memory!
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/3613921/KrnlDebug.txt)

**Comment by InfernalScorpion** [comment]
So when will this game be working?

**Comment by Margen67** [comment]
Duplicate of #467
