### ISSUE TITLE
Jet Set Radio Future - Game turn black when using "boost dash"

### ISSUE THREAD

**Issue by DrShadox** [Cxbx-Reloaded/game-compatibility#723]
### Description
The game turn black (except some HUD things) while using the "Boost Dash" ability , instead of having a "speed effect" , when ability is finished , the game come back to normal (so it's like a blind boost).

### Status
**Previous behavior:** 
'None reported'

**Current behavior:**
Game windows turn black (except HP bar + spray can counter + dash icon) , while using "Bosst Dash", in the original game on Xbox we got a blurry-speed effect and flame like on this screen : 
https://gyazo.com/d4252aa88148a72745da8ace169324df

### Screenshots
![image](https://user-images.githubusercontent.com/21160703/39073171-27fe2b1a-44ed-11e8-8367-73c853e3e224.png)

### Additional Information
I use "Cxbx-Reloaded 4fcbb494 (Apr 20 218)" and i've convert the "XBOX_Jet_Set_Radio_Future_PAL.iso" to Xbe with "C xbox tool" 
I'm on W10 

(sorry for my english , if i've miss some infos , please ask me).

**Comment by PatrickvL** [comment]
Radwolfie is right - we already have an issue for this. No need to have two, so closing this one.
