### ISSUE TITLE
Japan-only games that may/may not have the Japanese language in it

### ISSUE THREAD

**Issue by ObiKKa** [Cxbx-Reloaded/game-compatibility#727]
### Description
This issue may not be applicable to the issues tab here as it's meant for reporting compatibility status of software titles. But it may be replicated into a page under the Wiki tab (I cannot do it myself).

Admins, can you please add the purple '[language-japanese](https://github.com/Cxbx-Reloaded/game-compatibility/issues?utf8=%E2%9C%93&q=label%3Alanguage-japanese+)' label to almost all or all of the following issue pages below (I don't have the time right now to title them here but you can quickly click on them all). Sure, there is the possibility that some of these games below already have near-full or full English text on-screen (Maybe add the label 'probable-language-japanese'?). Hopefully I have not missed any other page.

### Dumps 

https://github.com/Cxbx-Reloaded/game-compatibility/issues/398
https://github.com/Cxbx-Reloaded/game-compatibility/issues/644
https://github.com/Cxbx-Reloaded/game-compatibility/issues/643
https://github.com/Cxbx-Reloaded/game-compatibility/issues/578
https://github.com/Cxbx-Reloaded/game-compatibility/issues/574
https://github.com/Cxbx-Reloaded/game-compatibility/issues/573
https://github.com/Cxbx-Reloaded/game-compatibility/issues/567
https://github.com/Cxbx-Reloaded/game-compatibility/issues/565
https://github.com/Cxbx-Reloaded/game-compatibility/issues/554
https://github.com/Cxbx-Reloaded/game-compatibility/issues/553
https://github.com/Cxbx-Reloaded/game-compatibility/issues/552
https://github.com/Cxbx-Reloaded/game-compatibility/issues/551
https://github.com/Cxbx-Reloaded/game-compatibility/issues/550
https://github.com/Cxbx-Reloaded/game-compatibility/issues/510
https://github.com/Cxbx-Reloaded/game-compatibility/issues/491
https://github.com/Cxbx-Reloaded/game-compatibility/issues/490
https://github.com/Cxbx-Reloaded/game-compatibility/issues/488
https://github.com/Cxbx-Reloaded/game-compatibility/issues/486
https://github.com/Cxbx-Reloaded/game-compatibility/issues/484
https://github.com/Cxbx-Reloaded/game-compatibility/issues/473
https://github.com/Cxbx-Reloaded/game-compatibility/issues/468
https://github.com/Cxbx-Reloaded/game-compatibility/issues/414
https://github.com/Cxbx-Reloaded/game-compatibility/issues/166
https://github.com/Cxbx-Reloaded/game-compatibility/issues/157
https://github.com/Cxbx-Reloaded/game-compatibility/issues/120
https://github.com/Cxbx-Reloaded/game-compatibility/issues/24
https://github.com/Cxbx-Reloaded/game-compatibility/issues/10

### Status
**Previous behavior:** 
Most of the Japan-only games currently listed under the Issues tab here lack the purple language-japan label. So I tried to find for all of them that could potentially contain Japanese language inside the games - i.e. gameplay text, menus, credits...

**Current behavior:**
Ideally, an admin can make a duplicate copy of this list onto the Wiki section. If they wish I can update this list here with additional possible titles (Or close it down). I'll try to title each of these issue above here at a later time.

### Additional Information
As we know, some of these mentioned games may actually have full English intact in the gameplay world and even the menus. But there is always the possibility to detect Japanese text characters in some screens/videos such as the control screen and end credits roll.

**Comment by Voxel9** [comment]
Done. I applied the `language-japan` tag to all of those issues for now. If you see any more that might need it, or if you don't think there should've been a tag applied to one of them, gimme a shout.

**Comment by Voxel9** [comment]
Should we be adding `language-japanese` to all of these? The screenshot from the issue for Loons - The Fight for Fame, and the fact there wasn't any signs of a Jap release on GFAQs/W.Pedia, makes me feel as if it doesn't  have any Japanese language. (The Crazy Taxi and FIFA screenshots are also completely in English; can someone confirm if they're Japanese by default?)

**Comment by ObiKKa** [comment]
Yeah. I know about the Loons issue. I can't find any confirmation anywhere. Maybe check auctions on ebay to see if there were Japanese cases of that game?

I saw that Crazy Taxi 3 ([GameFAQs](https://gamefaqs.gamespot.com/xbox/558595-crazy-taxi-3-high-roller/images), [Wiki](https://en.wikipedia.org/wiki/Crazy_Taxi_3:_High_Roller)) & [FIFA](https://gamefaqs.gamespot.com/xbox/555157-2002-fifa-world-cup/images) have their own Japanese releases.

**Comment by CakeLancelot** [comment]
I'm going to close this but keep notifications on, so if there are any issues that need updated you can comment them. There should probably be a better mechanism to report this though, maybe putting everything needed to change in the projects tab?

**Comment by ObiKKa** [comment]
Yes. How do I get into the projects tab? I have seen it before. But it's kinda hidden.
