### ISSUE TITLE
Kingdom Under Fire: The Crusaders - 

### ISSUE THREAD

**Issue by JCkido0o** [Cxbx-Reloaded/game-compatibility#729]
I've managed to get this title past the initial "Phantagram" splash screen / freeze, past the ESRB notice, and into the  "Kingdom Under Fire: The Crusaders" logo loading screen via these settings. these settings produced the highest framerate during the loading screens .

Audio: Uncheck all,
Video: uncheck use hardware mode, don't force v-sync, and check enable hardware YUV
LLE Experimental: enable LLE GPU 
Hacks: Disable pixel shader, Patch CPU, run on all cores, uncap framerate.

Hopefully someone who's a bit more clever can make this work,

Then of course, followed by an unknown error,
0xC0000005 @ EIP :=0x00000000(=unknown+0x0)

**Comment by CakeLancelot** [comment]
Moved into #720
