### ISSUE TITLE
Conflict: Global [5343000C]

### ISSUE THREAD

**Issue by Crimsom13** [Cxbx-Reloaded/game-compatibility#731]
Boots to menu, crash while loading in engine, some recent progress on error reporting. Also a dirty disk error while booting into main campaign.

![conflict vietnam](https://user-images.githubusercontent.com/38405862/39591570-292a42c8-4ed2-11e8-889b-5c70a33fa780.JPG)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1971891/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1971892/KrnlDebug.txt)

**Comment by Margen67** [comment]
Will reopen once Xbe dump is provided.
