### ISSUE TITLE
Conflict:Vietnam [5343000A]

### ISSUE THREAD

**Issue by Crimsom13** [Cxbx-Reloaded/game-compatibility#732]
Boots in menues, loads into in game cut-scenes then crashes on engine load.

-can't delete created save profiles.
-profiles sometimes cannot be read when loading. (might be completely fixed now)

![capture](https://user-images.githubusercontent.com/38405862/39591881-2039db5a-4ed3-11e8-991d-73fa72945cad.JPG)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1971917/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1971918/KrnlDebug.txt)

**Comment by blueshogun96** [comment]
This title used to go ingame in previous releases.  Time to do some backtracking...

Shogun

**Comment by Crimsom13** [comment]
Conflict desert storm 2 no longer goes ingame now has a dirty disk error that regressed not as long ago, Conflict vietname for as long as I've been following had a dirty disk error, some progression was made with being able to get past profile creation.

**Comment by Margen67** [comment]
Will reopen once Xbe dump is provided.
