### ISSUE TITLE
Superman Returns Xbox One doesnt work i get an error please fix

### ISSUE THREAD

**Issue by toozzb** [Cxbx-Reloaded/game-compatibility#739]
Hello

The most thing on this game i get an error and i dont know how to fix this kind of issue please fix this error i am unable to play this game, i hope you fix this for this game

OpenGL used to work on ps2 emulator but still glitchy i dont see that feature on this emulator

proof i was able to load it but afterwards crash

![dddd](https://user-images.githubusercontent.com/38509697/39739644-fee4cfc2-5289-11e8-93a4-0e2a5c1211c6.png)

![frfr](https://user-images.githubusercontent.com/38509697/39739548-60a6d328-5289-11e8-9426-4a6befc811b0.png)

**Comment by BenNottelling** [comment]
@toozzb sorry, but I had to edit and then close your issue. You provided an illegal link, and we can not support piracy. This report is also invalid as we do not know if that game had been modified
