### ISSUE TITLE
Mega Man Anniversary Collection [43430011]

### ISSUE THREAD

**Issue by Shideravan** [Cxbx-Reloaded/game-compatibility#743]
### Description

Unsupported

```---------------------------
Cxbx-Reloaded
---------------------------
Received Exception Code 0xC0000005 @ EIP := 0x04073377

  Press "OK" to terminate emulation.
  Press "Cancel" to debug.
---------------------------
OK   Cancel   
---------------------------
```

### Dumps 

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2019077/KrnlDebug.txt)

### Status
**Previous behavior:** 
N/A

**Current behavior:**
Nothing

### Additional Information

![image](https://user-images.githubusercontent.com/12163923/40264470-b93b883e-5afa-11e8-851d-94eee8a89bdf.png)

**Comment by haradons** [comment]
Figured I would show that Megaman 1-8 loads as of 46c079cf, however it does have some graphical issues, but overall can confirm that it works
![image](https://user-images.githubusercontent.com/13687549/40281316-23e61f44-5c15-11e8-9c5c-0ec1d8af9889.png)
![image](https://user-images.githubusercontent.com/13687549/40281323-3b08705a-5c15-11e8-9b3e-29e653a109a5.png)
![image](https://user-images.githubusercontent.com/13687549/40281350-866a7a5c-5c15-11e8-9e14-7a2f7637a257.png)
![image](https://user-images.githubusercontent.com/13687549/40281364-add4b1ac-5c15-11e8-9568-377e50244138.png)
![image](https://user-images.githubusercontent.com/13687549/40281411-e6d951ba-5c15-11e8-86f9-5e1e7c3c58e7.png)
![image](https://user-images.githubusercontent.com/13687549/40281419-18342988-5c16-11e8-98a8-241e8b64c92b.png)
![image](https://user-images.githubusercontent.com/13687549/40281424-41ba80cc-5c16-11e8-86bb-930c350d29bf.png)
![image](https://user-images.githubusercontent.com/13687549/40281445-a0b2a5dc-5c16-11e8-8b6c-b44c8ccf6a62.png)
![image](https://user-images.githubusercontent.com/13687549/40281453-c08ba2f0-5c16-11e8-924e-9f0c33b907c2.png)

**Comment by Margen67** [comment]
Will reopen once Xbe dump and KrnlDebug.txt are provided.
