### ISSUE TITLE
Star Wars - Obi-Wan not running?

### ISSUE THREAD

**Issue by WillNForce** [Cxbx-Reloaded/game-compatibility#744]
![emu](https://user-images.githubusercontent.com/39447961/40274461-67746a34-5ba4-11e8-91e6-3d62585e1ab5.jpg)

So I just got CXBXR and i'm trying to play Star Wars Obi-Wan
I click on the default.xbe file and the picture of obi-wan pops on the right corner but when i click to start the emulator it just says "Emulation Failed, if message repeats, the Xbe is not supported"

Anyone know why this might be happening of maybe a place i can download the game and it works?

**Comment by CakeLancelot** [comment]
Hi,

This question is more suited to the [Gitter](https://gitter.im/Cxbx-Reloaded/Lobby) or [Discord](https://discord.gg/26Xjx23) chat. Please only post reports here and keep support requests to these channels. There should be plenty of people to help troubleshoot your issue there.

Thanks

**Comment by PatrickvL** [comment]
Also : do not expect any support when asking for illegal downloads

**Comment by WillNForce** [comment]
i do have the actual game disc as well. i'd love to run it that way if someone could tell me what exactly i need to get to make this happen. been wanting to replay this game for years
