### ISSUE TITLE
Slam Tennis [49470011]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#75]
## Issues
* Used to reach the menus, but not anymore

_From @PatrickvL on July 27, 2017 8:13_

Reported by @blueshogun96 - need more details.

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#533_

**Comment by Margen67** [comment]
Closed due to being useless, as discussed in Discord:
```[2:44 AM] LukeUsher: They're not duplicates, but they don't have enough info to determine what version of the game the report is for.
[2:44 AM] LukeUsher: so they're useless```
