### ISSUE TITLE
Apex [Racing Evoluzione] [IG-021] [1.04]

### ISSUE THREAD

**Issue by SonicThePS4** [Cxbx-Reloaded/game-compatibility#775]
### Dumps 
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2033453/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2037456/KrnlDebug.txt)

**Current behavior:**
It has black screen with a Audio System Issue.

### Screenshots

![untitled](https://user-images.githubusercontent.com/39503785/40446073-02d52636-5e9c-11e8-87c6-fce628e757b9.png)

**Comment by SonicThePS4** [comment]
@Voxel9 Oh okay, how do I do that? :-o

**Comment by Voxel9** [comment]
To dump your XBE info, go to Edit -> Dump Xbe info to -> File..., save your xbe.txt somewhere, then drag, drop and upload here.
Similar for krnldebug.txt, go to View -> Debug Output (Kernel) -> File... then set a location to save it to, then you'll need to run the emulation again to generate it. Drag and drop it here like the xbe.txt afterwards then we're all good :)

**Comment by SonicThePS4** [comment]
@Voxel9 Oh okay I think, I did both of them. the xbe.txt and the karnldebug.txt should be exposing 
simultaneously, right? :o

**Comment by SonicThePS4** [comment]
@Voxel9 Ohh okay I got it alittle :D but the krnldebug.txt is kinda confusing. Should it show the same links, too?

**Comment by SonicThePS4** [comment]
@Voxel9 Ohh okay I got it alittle :D What should I place between these "()" on the KrnlDebug.txt?

**Comment by SonicThePS4** [comment]
Totally I did like what you said your steps work! :D but Apex didn't :(

**Comment by Voxel9** [comment]
Something I never realized until now is that there's already an issue for this game posted in #156, though this xbe's title is named "Apex", whereas the original issue's xbe's title is in all-caps "APEX", which makes me think that it could be a regional difference.
I'll mark this as a potential duplicate for now, but otherwise it'd be nice to know what specific region this issue is covering; unfortunately since this xbe is patched as "region free" it's not really possible to tell.

**Comment by SonicThePS4** [comment]
Ah, I see. I understand now. That might be why. I saw the Region status saying "Unknown."

**Comment by SonicThePS4** [comment]
Is getting there! It finally has a title screen showing! but, unfortunately the black screen continues to appear when you press start. But Sega GT 2002 is finally in-game along with Sega GT Online!

![image](https://user-images.githubusercontent.com/39503785/81799012-b6475480-94de-11ea-90a1-0454c80c820f.png)

**Comment by Margen67** [comment]
@SonicThePS4 Please provide a KrnlDebug.txt

**Comment by gandalfthewhite19890404** [comment]
How did you get to menus?
Did you used non-WIP branch?
Current on master:
![image](https://user-images.githubusercontent.com/24764335/82114237-9cbb3c80-976c-11ea-8ccb-f2b0345e5296.png)

**Comment by Margen67** [comment]
Closing this as a duplicate with a tampered xbe.
