### ISSUE TITLE
To CXBXR Team:

### ISSUE THREAD

**Issue by SonicThePS4** [Cxbx-Reloaded/game-compatibility#777]
### (Look at the Description, please.) 
This emulator is really amazing and swell done for low PC's. I played Dead Or Alive 3 & Jet Radio Future, and it is really done pretty well. I'm getting at least 45 to 60fps But in the next update, Is it possible that you guys can fix these Resolutions for weak PC's from the next update, please? Because I tried to dumb the graphics down by config the Resolutions to make my games to run smoother, but their all running the same. Or it'll be a tad a bit slower. But, A BIG Thanks to you guys for putting all hard work to this. That acceleration was Jaw Dropping Amazing.

```

```

### Status
**Previous behavior:** 

**Current behavior:**

### Screenshots

![untitled](https://user-images.githubusercontent.com/39503785/40519320-f40965da-5f8c-11e8-9f11-d236068dc42f.png)

### Additional Information

!

**Comment by CakeLancelot** [comment]
The Xbox runs natively at 640x480, so you cannot run it any lower. Furthermore, any feature requests should go on the [main repository's issue page](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues).

Closing this for now

**Comment by SonicThePS4** [comment]
@CakeLancelot Oh no, I mean when I try to click to 640x480, it runs slower for some reason.

**Comment by CakeLancelot** [comment]
> @CakeLancelot Oh no, I mean when I try to click to 640x480, it runs slower for some reason.

Might be down to margin of error, if you reliably reproduce this please do create a new issue in the main repository (link in previous comment).

**Comment by SonicThePS4** [comment]
Oh okay, so I can re-upload this to the main repository's issue page?
