### ISSUE TITLE
NHL 07

### ISSUE THREAD

**Issue by yawnbang** [Cxbx-Reloaded/game-compatibility#778]
Upon downloading a NHL 07 zip from a ROM website and unzipping I obtain a file with the game data and a default.xbe. When I select this xbe file and then select start emulation the fps= 0. 0 /f = 0.0  then after a few seconds the fps =1.23 and F = 322 which instantly jumps to fps=1.23 and F = 688.17.
The emulator screen remains black and no external screen appears.

**Comment by CakeLancelot** [comment]
Hello,

We cannot support illegally downloaded games here, as it is both a legal issue and may cause differences in emulation depending on patches applied.

Please obtain the files from an official game disc, then we can provide support. Keep in mind that Cxbx-Reloaded is also in early development, and has no guarantee of compatibility with games.

Thanks.
