### ISSUE TITLE
Jet Set Radio Future - crash when pressing B button (0xC0000005 @ EIP := 0x04073A0E)

### ISSUE THREAD

**Issue by alvarocaceresmunoz** [Cxbx-Reloaded/game-compatibility#785]
I am playing the introductory tutorial. When I press the boost dash (B) button, cxbxr hangs and outputs the following message:
0xC0000005 @ EIP := 0x04073A0E

Any thoughts on why could this happen?

**Comment by CakeLancelot** [comment]
Do you have the viewport scaling hack enabled? If so, disable it.

If this doesn't fix your issue please report this in #703. Closing this issue.

**Comment by Voxel9** [comment]
![image](https://user-images.githubusercontent.com/16278868/40714630-178b9222-63fb-11e8-9119-5d2251fc5ff5.png)
