### ISSUE TITLE
MX Unleashed PAL [54510021]

### ISSUE THREAD

**Issue by bhodg22** [Cxbx-Reloaded/game-compatibility#801]
### Description

Game boots and can reach menu, but just displays a black screen. Audio is working

### Dumps 
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2087505/KrnlDebug.txt)

### Status
**Previous behavior:** 

None Reported

**Current behavior:**

Audio working, black screen.

### Screenshots

![image](https://user-images.githubusercontent.com/5080749/41197636-f0e87818-6ca8-11e8-8fe9-3fe6a4b57e02.png)

### Additional Information

Backbuffer hack turned on, however same result if turned off.

Same result when cycling through display modes (F11)

**Comment by Margen67** [comment]
Closed due to being useless, as discussed on Discord:
```
[2:44 AM] LukeUsher: They're not duplicates, but they don't have enough info to determine what version of the game the report is for.
[2:44 AM] LukeUsher: so they're useless
```
