### ISSUE TITLE
TaoFeng - Fist of the Lotus.

### ISSUE THREAD

**Issue by SonicThePS4** [Cxbx-Reloaded/game-compatibility#840]
### Description

It's showing me this message.

```

```

### Dumps 
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2164474/Xbe.txt)

Sorry it won't let me dump the Kernel for some weird reason.

### Status
**Previous behavior:** 

**Current behavior:**

### Screenshots
![untitled](https://user-images.githubusercontent.com/39503785/42295780-e3ae12d6-7fbb-11e8-8a5c-d67c2721cb55.png)

**Comment by ergo720** [comment]
Isn't this a duplicate of #602? The TitleId of that dump is 0x4D530014 -> "MS-020" which is the same as this one

**Comment by SonicThePS4** [comment]
Ohh okay. But yeah it is.
