### ISSUE TITLE
About - Contributors (Error)

### ISSUE THREAD

**Issue by Mored1984** [Cxbx-Reloaded/game-compatibility#846]
### Description

The text is not showing right, see the picture below.

```
```

### Status
**Previous behavior:** 

**Current behavior:**

### Screenshots

![image](https://user-images.githubusercontent.com/5413459/42703665-e0815282-86d5-11e8-8060-4f9da177ad65.png)

Must be like the below picture

![image](https://user-images.githubusercontent.com/5413459/42703842-68bb66ba-86d6-11e8-8ecb-7fc27564cfb8.png)

### Additional Information

Why not show the names of patreon ?

**Comment by CakeLancelot** [comment]
> Why not show the names of patreon ?

They are shown under supporters, though the list has not been updated in some time.

This repository is only for reporting problems while running games, while the problems pointed out in your report would be more general. I've copied the contents of this issue to the [correct place](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1342), so this will be closed.
