### ISSUE TITLE
I don't know if its for the game or the emulator or what, but everytime I try to play Jet Set Radio Future it shows this and does nothing

### ISSUE THREAD

**Issue by superori33** [Cxbx-Reloaded/game-compatibility#848]
![captura](https://user-images.githubusercontent.com/41758391/43308739-cfcdc486-9182-11e8-9176-ee7b70f47f2d.PNG)

**Comment by LukeUsher** [comment]
You didn't follow the instructions: We need more information, and issues for Jet Set Radio future already exist. Please post in the relevant issue for the game that you have.

**Comment by superori33** [comment]
I DON'T HAVCE MORE FUCKING INFO, IT'S JUST CRASH EVEN IF ALL THE SETTINGS ARE IN FUCKING DEFAULT

**Comment by LukeUsher** [comment]
You do have more info: We don't know what version of the emulator you are using, or what version of the game you are using, if it's dumped properly, what operating system you have, etc.

We can't help you without that information.

**Comment by superori33** [comment]
The last stable version, windows 10. There's only 1 version of Jet Set Radio Future to download in every page. The people who play this game in the emulator all says the can play fine

**Comment by LukeUsher** [comment]
@superori33 there is more than one version of Jet Set Radio: In fact, there are three. 

SE-010 v1.01(USA)
SE-010 v1.03 (Japan)
IG-024 v1.01 (Europe)

We need to know which version you have, to even start to help you.
We also need to know if you've tried all the normal/recommended steps: Clearing the HLE cache, resetting  settings to default, etc.

It would also be helpful if you upload a KrnlDebug log generated by the emulator.

**Comment by superori33** [comment]
The Europe version.
I made the recommended steps every time I try to play the game (just to make sure if it was a configuration problem)

(How I can see the KrnlDebug log?)

**Comment by Margen67** [comment]
Duplicate of #703
