### ISSUE TITLE
Help me with this problem

### ISSUE THREAD

**Issue by Brayan25652** [Cxbx-Reloaded/game-compatibility#853]
---------------------------
Cxbx-Reloaded
---------------------------
Received Exception Code 0xC0000005 @ EIP := 0x00000000(=unknown+0x0)

  Press "OK" to terminate emulation.
  Press "Cancel" to debug.
---------------------------
Aceppt   Cancel  
---------------------------

(Conker LIVE and RELOADED

**Comment by LukeUsher** [comment]
FYI: this is not a support forum, it’s a compatibility database. And this game is not compatible with Cxbx-Reloaded at this moment in time, so there’s nothing to help with
