### ISSUE TITLE
Direct3D issue

### ISSUE THREAD

**Issue by MechWarriorZero** [Cxbx-Reloaded/game-compatibility#856]
having issue trying to run a xbox game

![error](https://user-images.githubusercontent.com/42954585/45009053-deb54680-afba-11e8-95fe-8f796826dff6.jpg)

**Comment by Voxel9** [comment]
![image](https://user-images.githubusercontent.com/16278868/45034273-eaeae380-b04e-11e8-83c2-661a86c3bed5.png)

At any rate, you need to choose "Direct3D HAL (hardware)" from the middle drop-down box.
If there are no options, then I don't know; you can ask for support over on their discord.

**Comment by MechWarriorZero** [comment]
There is nothing in the drop down
