### ISSUE TITLE
Chihiro HOD3AC(GDX-0001)and Ghost Squad(GDX-0012A)

### ISSUE THREAD

**Issue by dorminirko** [Cxbx-Reloaded/game-compatibility#864]
Description
boot game will get error
ERROR 11
JVS I/O board is not connected to the mian board.

Dumps
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2579126/Xbe.txt)

Status
Previous behavior:
None reported

Current behavior:
All black screen and show this text

**Comment by CakeLancelot** [comment]
Please create separate issues for each game, even if they have the same results.

**Comment by Hydreigon223** [comment]
The JVS I/O board isn't emulated, in this case 837-13551-92. Every Chihiro game requires this I/O board else the system would complain. This board has been well understood thanks to Mame and Demul.

All Chihiro gun games use the same Sega IR Type II gun setup also well understood too. Keep in mind the different program revisions. I myself despise a hacked version of Virtua Cop 3 that bypasses all the important checks and fakes inputs via an original xbox controller running on this emulator atm.

It will take some help from Mame team to run Chihiro properly in CxBx.

**Comment by LukeUsher** [comment]
Virtua Cop 3 is not hacked to use a standard Xbox controller, it actually does not require the JVS IO board! 

Most Chihiro games do require it, yes, but for some reason unknown only to the developers, Virtua Cop 3 actively checks for Xbox controllers and can use them. Nothing is faked, we didn’t hack anything or modify the game in any way.
