### ISSUE TITLE
Jet set radio future dialogue text is wrong size and out of place when using resolution higher than 480p.

### ISSUE THREAD

**Issue by gavros777** [Cxbx-Reloaded/game-compatibility#866]
Dont see this issue being reported anywhere and is a game breaker for me.
Hope you guys can fix it soon.

**Comment by LukeUsher** [comment]
This is expected, it happens on real hardware if you patch the game for 720p or higher too, the issue is not limited to this emulator.

**Comment by CakeLancelot** [comment]
As Luke said this is expected behavior, if you find any other issues please report it in the existing issues: [PAL ](https://github.com/Cxbx-Reloaded/game-compatibility/issues/703) [NTSC](https://github.com/Cxbx-Reloaded/game-compatibility/issues/409).

**Comment by PatrickvL** [comment]
If only there was a method to detect these unscaled elements, then we could scale them to fit the enlarged surface dimensions

**Comment by Margen67** [comment]
This has been fixed with the new native upscaling.
