### ISSUE TITLE
Jet Set Radio Future - Recieved Exception Code 0xC0000005 @ EIP := 0x001BCA4D(=CDirectSoundBuffer_SetBufferData+0x1c2dd)

### ISSUE THREAD

**Issue by jbassasin** [Cxbx-Reloaded/game-compatibility#869]
Just downloaded it and tried to run it, searched for error code fix to see if I could fix it, seems to be new error code. That or I am stupid, new to emulating. Tried to use debugger as it suggested, same error code pops up. I have nothing else installed except for the CXBX runner and the game file which is in xbe.

**Comment by PatrickvL** [comment]
Closing, since we can't condone piracy here.
