### ISSUE TITLE
Halo Demo [Halo, Exhibition Demo Disc (vol 1)] [XK-009] [1.02]

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/game-compatibility#882]
### Description
Bundled with [Exhibition Demo Disc (vol 1)](https://github.com/Cxbx-Reloaded/game-compatibility/issues/880)
* Black screen, can hear background music.
* Emulation lockup when try go ingame 90% of the time.

### Dumps
Xbe Dump: [Halo-Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/3076548/Halo-Xbe.txt)

Symbol Cache: [Halo-5f3aae76.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/3076550/Halo-5f3aae76.txt)

### Status
**Previous behavior:** 
N/A

**Current behavior:**
interactive; only get black screen.

### Screenshots
Rare chance to see ingame
![Halo-ingame](https://user-images.githubusercontent.com/3938312/56083637-43f0d600-5ded-11e9-986f-5df4dafaad1c.png)

### Additional Information
Tested with https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/670d90651c25a6a2c1cbc2d87f13745c4cd0d7a4

**Comment by Margen67** [comment]
Will reopen once a report with KrnlDebug.txt is posted.

**Comment by Margen67** [comment]
Duplicate of #773
