### ISSUE TITLE
doesn't run on windows 10 hp laptops

### ISSUE THREAD

**Issue by raderth** [Cxbx-Reloaded/game-compatibility#894]
### Description

```

```

### Status
**Previous behavior:** 

**Current behavior:**

**Comment by BenNottelling** [comment]
Closing as you didn't provide any information, plus what what little bit of information you've provided suggests it's an issue with your laptop and not Cxbx reloaded.
If you want help please provide a good report. 
Remember, Cxbx Reloaded will only run on 64 bit versions of Windows, and if you have a specific game that doesn't work there is likely already an issue created for it where you can add onto the report with your info such as debug logs.
