### ISSUE TITLE
Its not possible to play game form Windows share.

### ISSUE THREAD

**Issue by ruthan** [Cxbx-Reloaded/game-compatibility#899]
Im using network share for share for sharing my images for multiple machine, its working well with 95% of adavanced emulators with but this one.
  I get always fatal error, that is not possible to open *.xbe file, when i start the emulation from network share.

**Comment by CakeLancelot** [comment]
If this applies to all games versus just one, please make an issue in the main repository.
In fact, there is an existing issue covering this problem: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1450

Closing as invalid

**Comment by ruthan** [comment]
It would be better move it, but created new one..
