### ISSUE TITLE
Simpsons Hit And Run Still Having The Same Issue But Long Loading

### ISSUE THREAD

**Issue by RagdolllFan2005** [Cxbx-Reloaded/game-compatibility#910]
I Dont Know How To Fix it its on every version right now Please Fix it And Plus i was able to play games in hd at 720p

**Comment by CakeLancelot** [comment]
Again, this page is for tracking compatibility - not user support. Try the [Discord chat](https://discordapp.com/invite/26Xjx23) instead.
