### ISSUE TITLE
Need for Speed: Hot Pursuit 2 [NFS Hot Pursuit 2] [EA-040] [1.02]

### ISSUE THREAD

**Issue by mohsinous** [Cxbx-Reloaded/game-compatibility#920]
Description
Game start with red screen after pressing Start it goes ingame but no Text UI (via XQEMU i found out how to go ingame completely)!!!!

Dumps 

Status
Previous behavior:

Current behavior:

Screenshots
![Cxbx-Reloaded f7f7aee8 (Sep 10 2019) _ Emulating EA-040 v1 02 (Need for Speed_ Hot Pursuit 2) 9_10_2019 11_14_00 PM](https://user-images.githubusercontent.com/32609205/64641168-d9d27080-d420-11e9-9d69-bfe577f907c0.png)
![Cxbx-Reloaded f7f7aee8 (Sep 10 2019) _ Emulating EA-040 v1 02 (Need for Speed_ Hot Pursuit 2) 9_10_2019 11_14_14 PM](https://user-images.githubusercontent.com/32609205/64641176-ddfe8e00-d420-11e9-9dbf-4361ecc1a7b8.png)
![Cxbx-Reloaded f7f7aee8 (Sep 10 2019) _ Emulating EA-040 v1 02 (Need for Speed_ Hot Pursuit 2) 9_10_2019 11_14_26 PM](https://user-images.githubusercontent.com/32609205/64641188-e1921500-d420-11e9-86dd-f99b35e29c16.png)
![Cxbx-Reloaded f7f7aee8 (Sep 10 2019) _ Emulating EA-040 v1 02 (Need for Speed_ Hot Pursuit 2) 9_10_2019 11_14_37 PM](https://user-images.githubusercontent.com/32609205/64641191-e656c900-d420-11e9-825e-3d319691d272.png)
![Cxbx-Reloaded f7f7aee8 (Sep 10 2019) _ Emulating EA-040 v1 02 (Need for Speed_ Hot Pursuit 2) 9_10_2019 11_04_44 PM](https://user-images.githubusercontent.com/32609205/64641203-e9ea5000-d420-11e9-878d-bfc2fc8f52df.png)

Additional Information

**Comment by FranciscoCarlosJunior** [comment]
#784 duplicate
