### ISSUE TITLE
Tomb Raider: Legend [SC-253] [v1.02]

### ISSUE THREAD

**Issue by FranciscoSam** [Cxbx-Reloaded/game-compatibility#937]
### Description
Fails to Boot,Crash During Startup and Not Responding.And go back to Cxbx-Reloaded Menu

### Status
**Previous behavior:** 
None Reported

**Current behavior:**
Crashes and Fails to boot

### Screenshots
![2020_01_25_09_07_14_656x536](https://user-images.githubusercontent.com/52464858/73121724-8c7c1900-3f53-11ea-8565-5c8dc94d8e06.jpg)
![2020_01_25_09_07_24_656x536](https://user-images.githubusercontent.com/52464858/73121729-93a32700-3f53-11ea-9316-2a73382b4006.jpg)
![2020_01_25_09_07_30_656x536](https://user-images.githubusercontent.com/52464858/73121731-99990800-3f53-11ea-8015-9728bb6fbc6a.jpg)
![2020_01_25_09_07_40_656x536](https://user-images.githubusercontent.com/52464858/73121732-9dc52580-3f53-11ea-8104-3e69b9e6c668.jpg)
![2020_01_25_09_07_44_656x536](https://user-images.githubusercontent.com/52464858/73121736-a4ec3380-3f53-11ea-959f-e328e67654b4.jpg)

**Comment by Margen67** [comment]
@FranciscoSam You need to provide the xbe dump and KrnlDebug.

**Comment by Margen67** [comment]
Replaced with #1021
