### ISSUE TITLE
Still life issues in the textboxes

### ISSUE THREAD

**Issue by LuismaSP89** [Cxbx-Reloaded/game-compatibility#940]
### Description

Still life has a problem with the selection text boxes, "not the dialog text" you can see in the very beginning of the game, when you talk with the policeman, then you need to choose between 2 options "L or R buttons" but you can't see the text containing this options.

The game is completely playable aside from this.

```

```

### Status
**Previous behavior:** 

None reported until today. But the problem is happening since I started to use the emulator years ago.

**Current behavior:**

### Screenshots

![74368981-e47ca180-4dd4-11ea-9ef8-36b3262f0349](https://user-images.githubusercontent.com/12205048/74588953-5cc7aa80-5001-11ea-826f-1d0d40b8f2ce.jpg)

### Additional Information

No hacks enabled.
Windows 10 x64
i7 4790k
16GB DDR3
GTX 970

**Comment by LuismaSP89** [comment]
Note: All tested with default config

**Comment by Margen67** [comment]
Again, you didn't fill out the issue template or title it properly just like in #939.
Also, you didn't need to make a whole new issue for this.
