### ISSUE TITLE
Stake: Fortune Fighters

### ISSUE THREAD

**Issue by Reclaimer343** [Cxbx-Reloaded/game-compatibility#942]
I am seriously looking for this game to get started, as I have uncovered numerous unused content hidden within the game files. If anyone has any idea on how to get the game to run, (this game was originally developed for pc and has files from the pc version left in the game still) It would be revoloutionary. I want to rework the game into playing better, mod the graphics, etc. I know how to do all of these things, besides getting the game to start passed the menu. 

![image](https://user-images.githubusercontent.com/61610925/75617931-c7193880-5b33-11ea-82b6-76dbc0a120df.png)

![image](https://user-images.githubusercontent.com/61610925/75617977-cb922100-5b34-11ea-96a4-9c2d27f8b847.png)

### Additional Information
I activated speedhack "Run on all threads"
no matter what I do, the game will never load up the actual fighting mode. It only lets me run the menus. On an older version, from 2018, august of CXBX I got the game to stay stuck in the loading screen of a map, that's the closest I got the game to ALMOST start.
 the first image is the crash debug text.
The second one shows what happens after trying to start the game, all the textures start loading back and forth and glitch out until the game just crashes.

**Comment by Margen67** [comment]
You didn't fill out the template at all.

**Comment by Margen67** [comment]
Remade into #943.
