### ISSUE TITLE
StarCraft Ghost Xbox Build

### ISSUE THREAD

**Issue by bazik210** [Cxbx-Reloaded/game-compatibility#946]
Basicly no luck in loading anything after blizzard intro and sadly black screen.

**Comment by GXTX** [comment]
Unfortunately due to the intense rarity of that game (one of a kind) no-one will be able to help, this is an invalid issue due that and you're missing required information. Do not open another issue on this game.

**Comment by bazik210** [comment]
Okey, sad, sorry for bothering, it's still avaliable to download if you know where to find, sad only xbox users can try it.
