### ISSUE TITLE
Crimson Skies [BBD40BD2] MS-033 [1.01]

### ISSUE THREAD

**Issue by Dragonslayer182** [Cxbx-Reloaded/game-compatibility#953]
### Description
Menus work fine besides the background of the main menu, which has the "hall of mirrors" effect. Black loading screen with visible spinning loader after loading a game. In-game, only the HUD and Skybox are visible, no models or environment is rendered. FMV's work correctly. Framerate hovers around 4-5 fps in-game on Ryzen 5 1600/16gb ram/1080ti, but changing process affinity for cxbx to realtime bumps it up to 7. "Looking" up increases the framerate drastically. It would freeze occasionally, though this seems to be triggered by switching windows on my computer, so possibly an emulator issue. Game seems to work fine otherwise, including sound. 

### Dumps 
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4438209/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4438237/KrnlDebug.txt)

### Status
**Previous behavior:** 
Game crashes with an error message. (Issue 452, not my submission.)

**Current behavior:**
Game does not render any models or environments, only menu/hud elements and the skybox. Main menu background and loading screens (Other than the pre-main menu loading screen) does not render.

### Screenshots
![image](https://user-images.githubusercontent.com/63237761/78557098-ce3c0200-77d5-11ea-8ea1-51fb60f1a359.png)

![image](https://user-images.githubusercontent.com/63237761/78557131-db58f100-77d5-11ea-9982-46ab5f968db6.png)

![image](https://user-images.githubusercontent.com/63237761/78557231-03e0eb00-77d6-11ea-8695-b429d9a941a4.png)

![image](https://user-images.githubusercontent.com/63237761/78557320-2d9a1200-77d6-11ea-9744-8a7da076d179.png)

### Additional Information

Version bbd40bd2 (Apr  6 2020)

Use all cores, Disable pixel shaders, and Skip RDTSC patching are enabled, however this only seems to unlock the game speed. Without it, the game behaves exactly the same except at normal speed (not framerate)

**Comment by Dragonslayer182** [comment]
Replied to the original issue, sorry I'm new to this.

**Comment by Margen67** [comment]
Duplicate of #452
