### ISSUE TITLE
Yu-Gi-Oh The Dawn of Destiny

### ISSUE THREAD

**Issue by marcosviniciusmv** [Cxbx-Reloaded/game-compatibility#960]
YuGiOh, in the compilation CI-f3d7ae6, I managed several duels and the FPS drops dramatically when it will choose a statue to win some card but still not crash. Well, I don't know if it helps, but I only managed to play
these duels specifically in that build. In any other build it crashes after the first duel and the emulation stops.

**Comment by Margen67** [comment]
Duplicate of #411
