### ISSUE TITLE
Final Fight Streetwise [CC-019] [v1.01]

### ISSUE THREAD

**Issue by Hadocem** [Cxbx-Reloaded/game-compatibility#962]
### Description
Game is in-game, because I can play it, but I can't see the characters, and just a little bit of the scenery.

### Dumps
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4607217/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4607274/KrnlDebug.txt)

### Screenshots
![](https://user-images.githubusercontent.com/28853392/81518097-50f33800-9313-11ea-9c7a-c83e71693b81.png)
![](https://user-images.githubusercontent.com/28853392/81518099-52246500-9313-11ea-96b7-debe475a2126.png)
![](https://user-images.githubusercontent.com/28853392/81518101-52bcfb80-9313-11ea-8a2a-d5c1e798eadc.png)
![](https://user-images.githubusercontent.com/28853392/81518103-53559200-9313-11ea-92ea-2e781cacac4f.png)
![](https://user-images.githubusercontent.com/28853392/81518105-53ee2880-9313-11ea-8900-e293216b50e2.png)
![](https://user-images.githubusercontent.com/28853392/81518107-551f5580-9313-11ea-9dfe-f8fa979090e9.png)
![](https://user-images.githubusercontent.com/28853392/81519189-c4e30f80-9316-11ea-805f-6a1b872204bf.png)

### Additional Information
CPU:  Intel Core i5 8400 2.8GHz (4.0GHz Turbo) 6-Core 6-Thread
RAM: DDR4 Crucial Ballistix Sport Lt, 16GB 3200MHz
GPU: GTX 1050Ti
Motherboard: Asus Z390-p
PSU: Gamemax GM600 600W
Water Cooler:  Mymax Algor, LED Red 120mm.

**Comment by RadWolfie** [comment]
@Hadocem Please do not report title's state from active/cancelled pull requests' builds in compatibility repository, thanks!

**Comment by Margen67** [comment]
Replaced by #1058
