### ISSUE TITLE
Mortal Kombat: Armageddon [MW-052] [1.02]

### ISSUE THREAD

**Issue by vorotnique** [Cxbx-Reloaded/game-compatibility#965]
### Description
The game emulates similar to MK Deception. Same missing HUD and main menu backgrounds.

### Dumps
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4645261/Xbe.txt) (region-free patched)

### Status
**Previous behavior:**

**Current behavior:**

### Screenshots
![menu](https://user-images.githubusercontent.com/55318399/82153818-84cde080-9872-11ea-9858-c839df81bcce.jpg)

Although, unlike MK Deception, this time we can create a profile without crashing, which means we may test Konquest Mode. It works nearly perfect until the main character appears and spreads glitchy graphics.
![konquest](https://user-images.githubusercontent.com/55318399/82153858-bcd52380-9872-11ea-92de-547383005d7c.jpg)
![taven](https://user-images.githubusercontent.com/55318399/82153860-bfd01400-9872-11ea-8bbd-2bb0f3d76559.jpg)

Motor Kombat and Krypt look nice, so I didn't make any troubleshooting screenshots.
As for main arcade mode, some models are ok, like Scorpion.
![selectscreen](https://user-images.githubusercontent.com/55318399/82153890-f27a0c80-9872-11ea-99b1-98479ea5b6a1.jpg)

Some fighters are glitchy like Reptile:
![reptile](https://user-images.githubusercontent.com/55318399/82153899-ff96fb80-9872-11ea-8543-62bc14269492.jpg)

Some arenas are OK like Tekunin Warship (pay attention to that weird shadow square under Sub-Zero).
![tekunin](https://user-images.githubusercontent.com/55318399/82153923-21907e00-9873-11ea-84ac-5385ba3aba13.jpg)

Some arenas don't look proper, like Bell Tower.
![belltower](https://user-images.githubusercontent.com/55318399/82153932-310fc700-9873-11ea-9ddd-4a8dc3f4c58f.jpg)

And here comes the main problem, which combines MK Deception, MK Armageddon and MK Shaolin Monks: black overlay after a few minutes of gameplay. In my 3rd battle, i got this:
![blackoverlay](https://user-images.githubusercontent.com/55318399/82153961-64525600-9873-11ea-871f-2dc6f558158a.jpg)
FPS dropped from 41 to 11. If I finish the battle, that black square will return in another one. In Deception, it's 40% wide and 100% high. In Shaolin Monks, it covers the whole space.

### Additional Information
Sound: just like Deception. Sounds are present, except background music.

**Comment by vorotnique** [comment]
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4645256/Xbe.txt)

**Comment by vorotnique** [comment]
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4645261/Xbe.txt)

**Comment by ObiKKa** [comment]
Version: [v1.02]
Label: region-free
XDK library package: 5849

Optional: you could also add the '7' number denoting this game as the 7th core MK title in the heading. Initial release in late 2006.

Other MK games here:
- Mortal Kombat [5]: Deadly Alliance (First released in late 2002)
- Mortal Kombat: Shaolin Monks (Brawler spin-off. First released in late 2005.)
- Mortal Kombat [6]: Deception (First released in late 2004)

**Comment by vorotnique** [comment]
> Label: region-free

Region is originally USA (NTSC), I have my image patched since there were no PAL releases of MKA.

**Comment by Margen67** [comment]
@vorotnique Please use the template next time.

**Comment by Margen67** [comment]
Reopening once a proper report with a KrnlDebug.txt is posted.

**Comment by Margen67** [comment]
Replaced with #1023
