### ISSUE TITLE
Sonic The Hedghehog Extreme [00000000] [v1.00]

### ISSUE THREAD

**Issue by TailsAndSonicFan** [Cxbx-Reloaded/game-compatibility#997]
![Untitled design](https://user-images.githubusercontent.com/66907346/84592843-5bff2380-adfd-11ea-92cd-9a4a52c99a69.png)

This Game Has So Ploblems With This Emulator At All Its Completly Playable At 60 Fps

**Comment by Margen67** [comment]
Trying reading next time:
> READ THE README BEFORE SUBMITTING AN ISSUE!
IF YOU'RE HERE TO CREATE AN ISSUE ASKING FOR SUPPORT, YOU'RE IN THE WRONG PLACE.

Also, Stop Typing Like This. It's obnoxious.
